//
//  BurgerSK.swift
//  Weshapp
//
//  Created by SM on 24/03/2015.
//  Copyright (c) 2015 Weshapp. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class BurgerSK : NSObject {

    //// Drawing Methods

    public class func drawBurger(#frame: CGRect, clicked: Bool, notclicked: Bool) {
        //// Color Declarations
        let color = UIColor(red: 0.647, green: 0.878, blue: 0.914, alpha: 1.000)
        let hamburgerSortColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)

        if (notclicked) {
            //// hamburger sort Drawing
            var hamburgerSortPath = UIBezierPath()
            hamburgerSortPath.moveToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + -0.00000 * frame.height))
            hamburgerSortPath.addLineToPoint(CGPointMake(frame.minX + 0.95119 * frame.width, frame.minY + -0.00000 * frame.height))
            hamburgerSortPath.addLineToPoint(CGPointMake(frame.minX + 0.95119 * frame.width, frame.minY + 0.09916 * frame.height))
            hamburgerSortPath.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.09916 * frame.height))
            hamburgerSortPath.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + -0.00000 * frame.height))
            hamburgerSortPath.closePath()
            hamburgerSortPath.moveToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.42968 * frame.height))
            hamburgerSortPath.addLineToPoint(CGPointMake(frame.minX + 0.95119 * frame.width, frame.minY + 0.42968 * frame.height))
            hamburgerSortPath.addLineToPoint(CGPointMake(frame.minX + 0.95119 * frame.width, frame.minY + 0.52883 * frame.height))
            hamburgerSortPath.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.52883 * frame.height))
            hamburgerSortPath.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.42968 * frame.height))
            hamburgerSortPath.closePath()
            hamburgerSortPath.moveToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.82630 * frame.height))
            hamburgerSortPath.addLineToPoint(CGPointMake(frame.minX + 0.95119 * frame.width, frame.minY + 0.82630 * frame.height))
            hamburgerSortPath.addLineToPoint(CGPointMake(frame.minX + 0.95119 * frame.width, frame.minY + 0.89695 * frame.height))
            hamburgerSortPath.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.89695 * frame.height))
            hamburgerSortPath.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.82630 * frame.height))
            hamburgerSortPath.closePath()
            hamburgerSortColor.setFill()
            hamburgerSortPath.fill()
        }


        if (clicked) {
            //// hamburger sort 2 Drawing
            var hamburgerSort2Path = UIBezierPath()
            hamburgerSort2Path.moveToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.00000 * frame.height))
            hamburgerSort2Path.addLineToPoint(CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + -0.00000 * frame.height))
            hamburgerSort2Path.addLineToPoint(CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + 0.10715 * frame.height))
            hamburgerSort2Path.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.10715 * frame.height))
            hamburgerSort2Path.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.00000 * frame.height))
            hamburgerSort2Path.closePath()
            hamburgerSort2Path.moveToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.46430 * frame.height))
            hamburgerSort2Path.addLineToPoint(CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + 0.46430 * frame.height))
            hamburgerSort2Path.addLineToPoint(CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + 0.57143 * frame.height))
            hamburgerSort2Path.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.57143 * frame.height))
            hamburgerSort2Path.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.46430 * frame.height))
            hamburgerSort2Path.closePath()
            hamburgerSort2Path.moveToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.89287 * frame.height))
            hamburgerSort2Path.addLineToPoint(CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + 0.89287 * frame.height))
            hamburgerSort2Path.addLineToPoint(CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + 1.00000 * frame.height))
            hamburgerSort2Path.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 1.00000 * frame.height))
            hamburgerSort2Path.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.89287 * frame.height))
            hamburgerSort2Path.closePath()
            color.setFill()
            hamburgerSort2Path.fill()
        }
    }

}
