//
//  CrossIconSK.swift
//  Weshapp
//
//  Created by SM on 22/01/2015.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class CrossIconSK : NSObject {

    //// Drawing Methods

    public class func drawCanvas1(#frame: CGRect, whiteBool: Bool, tintBool: Bool) {
        //// Color Declarations
        let plusIconCopyColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let color = UIColor(red: 0.647, green: 0.878, blue: 0.914, alpha: 1.000)

        if (tintBool) {
            //// Plus icon copy 2 Drawing
            var plusIconCopy2Path = UIBezierPath()
            plusIconCopy2Path.moveToPoint(CGPointMake(frame.minX + 0.48533 * frame.width, frame.minY + 0.11096 * frame.height))
            plusIconCopy2Path.addCurveToPoint(CGPointMake(frame.minX + 0.83908 * frame.width, frame.minY + 0.49940 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.68039 * frame.width, frame.minY + 0.11096 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.83908 * frame.width, frame.minY + 0.28522 * frame.height))
            plusIconCopy2Path.addCurveToPoint(CGPointMake(frame.minX + 0.48533 * frame.width, frame.minY + 0.88871 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.83908 * frame.width, frame.minY + 0.71359 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.68039 * frame.width, frame.minY + 0.88871 * frame.height))
            plusIconCopy2Path.addCurveToPoint(CGPointMake(frame.minX + 0.31489 * frame.width, frame.minY + 0.84038 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.42358 * frame.width, frame.minY + 0.88871 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.36547 * frame.width, frame.minY + 0.87116 * frame.height))
            plusIconCopy2Path.addCurveToPoint(CGPointMake(frame.minX + 0.13158 * frame.width, frame.minY + 0.49940 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.20570 * frame.width, frame.minY + 0.77392 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.13158 * frame.width, frame.minY + 0.64578 * frame.height))
            plusIconCopy2Path.addCurveToPoint(CGPointMake(frame.minX + 0.48533 * frame.width, frame.minY + 0.11096 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.13158 * frame.width, frame.minY + 0.28522 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.29027 * frame.width, frame.minY + 0.11096 * frame.height))
            plusIconCopy2Path.closePath()
            plusIconCopy2Path.moveToPoint(CGPointMake(frame.minX + 0.48532 * frame.width, frame.minY + 0.06742 * frame.height))
            plusIconCopy2Path.addCurveToPoint(CGPointMake(frame.minX + 0.09197 * frame.width, frame.minY + 0.49973 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.26808 * frame.width, frame.minY + 0.06742 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.09197 * frame.width, frame.minY + 0.26098 * frame.height))
            plusIconCopy2Path.addCurveToPoint(CGPointMake(frame.minX + 0.48532 * frame.width, frame.minY + 0.93203 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.09197 * frame.width, frame.minY + 0.73849 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.26808 * frame.width, frame.minY + 0.93203 * frame.height))
            plusIconCopy2Path.addCurveToPoint(CGPointMake(frame.minX + 0.87867 * frame.width, frame.minY + 0.49973 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.70257 * frame.width, frame.minY + 0.93203 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.87867 * frame.width, frame.minY + 0.73849 * frame.height))
            plusIconCopy2Path.addCurveToPoint(CGPointMake(frame.minX + 0.48532 * frame.width, frame.minY + 0.06742 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.87867 * frame.width, frame.minY + 0.26098 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.70257 * frame.width, frame.minY + 0.06742 * frame.height))
            plusIconCopy2Path.addLineToPoint(CGPointMake(frame.minX + 0.48532 * frame.width, frame.minY + 0.06742 * frame.height))
            plusIconCopy2Path.closePath()
            plusIconCopy2Path.moveToPoint(CGPointMake(frame.minX + 0.37434 * frame.width, frame.minY + 0.34705 * frame.height))
            plusIconCopy2Path.addLineToPoint(CGPointMake(frame.minX + 0.62458 * frame.width, frame.minY + 0.62208 * frame.height))
            plusIconCopy2Path.addCurveToPoint(CGPointMake(frame.minX + 0.62458 * frame.width, frame.minY + 0.65264 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.63226 * frame.width, frame.minY + 0.63052 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.63226 * frame.width, frame.minY + 0.64420 * frame.height))
            plusIconCopy2Path.addCurveToPoint(CGPointMake(frame.minX + 0.59678 * frame.width, frame.minY + 0.65263 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.61690 * frame.width, frame.minY + 0.66108 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.60446 * frame.width, frame.minY + 0.66107 * frame.height))
            plusIconCopy2Path.addLineToPoint(CGPointMake(frame.minX + 0.34653 * frame.width, frame.minY + 0.37761 * frame.height))
            plusIconCopy2Path.addCurveToPoint(CGPointMake(frame.minX + 0.34653 * frame.width, frame.minY + 0.34706 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.33886 * frame.width, frame.minY + 0.36917 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.33885 * frame.width, frame.minY + 0.35549 * frame.height))
            plusIconCopy2Path.addCurveToPoint(CGPointMake(frame.minX + 0.37434 * frame.width, frame.minY + 0.34705 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.35421 * frame.width, frame.minY + 0.33862 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.36666 * frame.width, frame.minY + 0.33862 * frame.height))
            plusIconCopy2Path.closePath()
            plusIconCopy2Path.moveToPoint(CGPointMake(frame.minX + 0.62458 * frame.width, frame.minY + 0.37761 * frame.height))
            plusIconCopy2Path.addLineToPoint(CGPointMake(frame.minX + 0.37433 * frame.width, frame.minY + 0.65263 * frame.height))
            plusIconCopy2Path.addCurveToPoint(CGPointMake(frame.minX + 0.34653 * frame.width, frame.minY + 0.65264 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.36665 * frame.width, frame.minY + 0.66108 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.35421 * frame.width, frame.minY + 0.66108 * frame.height))
            plusIconCopy2Path.addCurveToPoint(CGPointMake(frame.minX + 0.34653 * frame.width, frame.minY + 0.62208 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.33885 * frame.width, frame.minY + 0.64420 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.33885 * frame.width, frame.minY + 0.63052 * frame.height))
            plusIconCopy2Path.addLineToPoint(CGPointMake(frame.minX + 0.59677 * frame.width, frame.minY + 0.34705 * frame.height))
            plusIconCopy2Path.addCurveToPoint(CGPointMake(frame.minX + 0.62458 * frame.width, frame.minY + 0.34706 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.60445 * frame.width, frame.minY + 0.33862 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.61690 * frame.width, frame.minY + 0.33862 * frame.height))
            plusIconCopy2Path.addCurveToPoint(CGPointMake(frame.minX + 0.62458 * frame.width, frame.minY + 0.37761 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.63226 * frame.width, frame.minY + 0.35549 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.63226 * frame.width, frame.minY + 0.36917 * frame.height))
            plusIconCopy2Path.closePath()
            color.setFill()
            plusIconCopy2Path.fill()
        }


        if (whiteBool) {
            //// Plus icon copy Drawing
            var plusIconCopyPath = UIBezierPath()
            plusIconCopyPath.moveToPoint(CGPointMake(frame.minX + 0.48533 * frame.width, frame.minY + 0.11096 * frame.height))
            plusIconCopyPath.addCurveToPoint(CGPointMake(frame.minX + 0.83908 * frame.width, frame.minY + 0.49940 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.68039 * frame.width, frame.minY + 0.11096 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.83908 * frame.width, frame.minY + 0.28522 * frame.height))
            plusIconCopyPath.addCurveToPoint(CGPointMake(frame.minX + 0.48533 * frame.width, frame.minY + 0.88871 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.83908 * frame.width, frame.minY + 0.71359 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.68039 * frame.width, frame.minY + 0.88871 * frame.height))
            plusIconCopyPath.addCurveToPoint(CGPointMake(frame.minX + 0.31489 * frame.width, frame.minY + 0.84038 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.42358 * frame.width, frame.minY + 0.88871 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.36547 * frame.width, frame.minY + 0.87116 * frame.height))
            plusIconCopyPath.addCurveToPoint(CGPointMake(frame.minX + 0.13158 * frame.width, frame.minY + 0.49940 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.20570 * frame.width, frame.minY + 0.77392 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.13158 * frame.width, frame.minY + 0.64578 * frame.height))
            plusIconCopyPath.addCurveToPoint(CGPointMake(frame.minX + 0.48533 * frame.width, frame.minY + 0.11096 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.13158 * frame.width, frame.minY + 0.28522 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.29027 * frame.width, frame.minY + 0.11096 * frame.height))
            plusIconCopyPath.closePath()
            plusIconCopyPath.moveToPoint(CGPointMake(frame.minX + 0.48532 * frame.width, frame.minY + 0.06742 * frame.height))
            plusIconCopyPath.addCurveToPoint(CGPointMake(frame.minX + 0.09197 * frame.width, frame.minY + 0.49973 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.26808 * frame.width, frame.minY + 0.06742 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.09197 * frame.width, frame.minY + 0.26098 * frame.height))
            plusIconCopyPath.addCurveToPoint(CGPointMake(frame.minX + 0.48532 * frame.width, frame.minY + 0.93203 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.09197 * frame.width, frame.minY + 0.73849 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.26808 * frame.width, frame.minY + 0.93203 * frame.height))
            plusIconCopyPath.addCurveToPoint(CGPointMake(frame.minX + 0.87867 * frame.width, frame.minY + 0.49973 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.70257 * frame.width, frame.minY + 0.93203 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.87867 * frame.width, frame.minY + 0.73849 * frame.height))
            plusIconCopyPath.addCurveToPoint(CGPointMake(frame.minX + 0.48532 * frame.width, frame.minY + 0.06742 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.87867 * frame.width, frame.minY + 0.26098 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.70257 * frame.width, frame.minY + 0.06742 * frame.height))
            plusIconCopyPath.addLineToPoint(CGPointMake(frame.minX + 0.48532 * frame.width, frame.minY + 0.06742 * frame.height))
            plusIconCopyPath.closePath()
            plusIconCopyPath.moveToPoint(CGPointMake(frame.minX + 0.37434 * frame.width, frame.minY + 0.34705 * frame.height))
            plusIconCopyPath.addLineToPoint(CGPointMake(frame.minX + 0.62458 * frame.width, frame.minY + 0.62208 * frame.height))
            plusIconCopyPath.addCurveToPoint(CGPointMake(frame.minX + 0.62458 * frame.width, frame.minY + 0.65264 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.63226 * frame.width, frame.minY + 0.63052 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.63226 * frame.width, frame.minY + 0.64420 * frame.height))
            plusIconCopyPath.addCurveToPoint(CGPointMake(frame.minX + 0.59678 * frame.width, frame.minY + 0.65263 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.61690 * frame.width, frame.minY + 0.66108 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.60446 * frame.width, frame.minY + 0.66107 * frame.height))
            plusIconCopyPath.addLineToPoint(CGPointMake(frame.minX + 0.34653 * frame.width, frame.minY + 0.37761 * frame.height))
            plusIconCopyPath.addCurveToPoint(CGPointMake(frame.minX + 0.34653 * frame.width, frame.minY + 0.34706 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.33886 * frame.width, frame.minY + 0.36917 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.33885 * frame.width, frame.minY + 0.35549 * frame.height))
            plusIconCopyPath.addCurveToPoint(CGPointMake(frame.minX + 0.37434 * frame.width, frame.minY + 0.34705 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.35421 * frame.width, frame.minY + 0.33862 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.36666 * frame.width, frame.minY + 0.33862 * frame.height))
            plusIconCopyPath.closePath()
            plusIconCopyPath.moveToPoint(CGPointMake(frame.minX + 0.62458 * frame.width, frame.minY + 0.37761 * frame.height))
            plusIconCopyPath.addLineToPoint(CGPointMake(frame.minX + 0.37433 * frame.width, frame.minY + 0.65263 * frame.height))
            plusIconCopyPath.addCurveToPoint(CGPointMake(frame.minX + 0.34653 * frame.width, frame.minY + 0.65264 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.36665 * frame.width, frame.minY + 0.66108 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.35421 * frame.width, frame.minY + 0.66108 * frame.height))
            plusIconCopyPath.addCurveToPoint(CGPointMake(frame.minX + 0.34653 * frame.width, frame.minY + 0.62208 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.33885 * frame.width, frame.minY + 0.64420 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.33885 * frame.width, frame.minY + 0.63052 * frame.height))
            plusIconCopyPath.addLineToPoint(CGPointMake(frame.minX + 0.59677 * frame.width, frame.minY + 0.34705 * frame.height))
            plusIconCopyPath.addCurveToPoint(CGPointMake(frame.minX + 0.62458 * frame.width, frame.minY + 0.34706 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.60445 * frame.width, frame.minY + 0.33862 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.61690 * frame.width, frame.minY + 0.33862 * frame.height))
            plusIconCopyPath.addCurveToPoint(CGPointMake(frame.minX + 0.62458 * frame.width, frame.minY + 0.37761 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.63226 * frame.width, frame.minY + 0.35549 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.63226 * frame.width, frame.minY + 0.36917 * frame.height))
            plusIconCopyPath.closePath()
            plusIconCopyColor.setFill()
            plusIconCopyPath.fill()
        }
    }

}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
