//
//  CrossSK.swift
//  Weshapp
//
//  Created by SM on 24/03/2015.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class CrossSK : NSObject {

    //// Drawing Methods

    public class func drawCrossCanvas(#frame: CGRect, clicked: Bool, notClicked: Bool) {
        //// Color Declarations
        let plusIconCopyColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let color = UIColor(red: 0.647, green: 0.878, blue: 0.914, alpha: 1.000)

        if (clicked) {
            //// clickedCross Drawing
            var clickedCrossPath = UIBezierPath()
            clickedCrossPath.moveToPoint(CGPointMake(frame.minX + 0.49477 * frame.width, frame.minY + 0.05111 * frame.height))
            clickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.93015 * frame.width, frame.minY + 0.49931 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.73484 * frame.width, frame.minY + 0.05111 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.93015 * frame.width, frame.minY + 0.25217 * frame.height))
            clickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.49477 * frame.width, frame.minY + 0.94851 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.93015 * frame.width, frame.minY + 0.74645 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.73484 * frame.width, frame.minY + 0.94851 * frame.height))
            clickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.28500 * frame.width, frame.minY + 0.89274 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.41877 * frame.width, frame.minY + 0.94851 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.34725 * frame.width, frame.minY + 0.92826 * frame.height))
            clickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.05938 * frame.width, frame.minY + 0.49931 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.15061 * frame.width, frame.minY + 0.81606 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.05938 * frame.width, frame.minY + 0.66821 * frame.height))
            clickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.49477 * frame.width, frame.minY + 0.05111 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.05938 * frame.width, frame.minY + 0.25217 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.25469 * frame.width, frame.minY + 0.05111 * frame.height))
            clickedCrossPath.closePath()
            clickedCrossPath.moveToPoint(CGPointMake(frame.minX + 0.49475 * frame.width, frame.minY + 0.00087 * frame.height))
            clickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.01063 * frame.width, frame.minY + 0.49969 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.22738 * frame.width, frame.minY + 0.00087 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.01063 * frame.width, frame.minY + 0.22421 * frame.height))
            clickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.49475 * frame.width, frame.minY + 0.99849 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.01063 * frame.width, frame.minY + 0.77518 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.22738 * frame.width, frame.minY + 0.99849 * frame.height))
            clickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.97888 * frame.width, frame.minY + 0.49969 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.76214 * frame.width, frame.minY + 0.99849 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.97888 * frame.width, frame.minY + 0.77518 * frame.height))
            clickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.49475 * frame.width, frame.minY + 0.00087 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.97888 * frame.width, frame.minY + 0.22421 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.76214 * frame.width, frame.minY + 0.00087 * frame.height))
            clickedCrossPath.addLineToPoint(CGPointMake(frame.minX + 0.49475 * frame.width, frame.minY + 0.00087 * frame.height))
            clickedCrossPath.closePath()
            clickedCrossPath.moveToPoint(CGPointMake(frame.minX + 0.35816 * frame.width, frame.minY + 0.32352 * frame.height))
            clickedCrossPath.addLineToPoint(CGPointMake(frame.minX + 0.66615 * frame.width, frame.minY + 0.64086 * frame.height))
            clickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.66615 * frame.width, frame.minY + 0.67612 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.67560 * frame.width, frame.minY + 0.65059 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.67560 * frame.width, frame.minY + 0.66638 * frame.height))
            clickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.63193 * frame.width, frame.minY + 0.67612 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.65670 * frame.width, frame.minY + 0.68586 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.64138 * frame.width, frame.minY + 0.68585 * frame.height))
            clickedCrossPath.addLineToPoint(CGPointMake(frame.minX + 0.32394 * frame.width, frame.minY + 0.35878 * frame.height))
            clickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.32393 * frame.width, frame.minY + 0.32353 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.31449 * frame.width, frame.minY + 0.34904 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.31448 * frame.width, frame.minY + 0.33326 * frame.height))
            clickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.35816 * frame.width, frame.minY + 0.32352 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.33338 * frame.width, frame.minY + 0.31379 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.34871 * frame.width, frame.minY + 0.31379 * frame.height))
            clickedCrossPath.closePath()
            clickedCrossPath.moveToPoint(CGPointMake(frame.minX + 0.66615 * frame.width, frame.minY + 0.35878 * frame.height))
            clickedCrossPath.addLineToPoint(CGPointMake(frame.minX + 0.35816 * frame.width, frame.minY + 0.67612 * frame.height))
            clickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.32394 * frame.width, frame.minY + 0.67612 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.34870 * frame.width, frame.minY + 0.68586 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.33339 * frame.width, frame.minY + 0.68586 * frame.height))
            clickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.32393 * frame.width, frame.minY + 0.64086 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.31448 * frame.width, frame.minY + 0.66638 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.31448 * frame.width, frame.minY + 0.65060 * frame.height))
            clickedCrossPath.addLineToPoint(CGPointMake(frame.minX + 0.63193 * frame.width, frame.minY + 0.32352 * frame.height))
            clickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.66615 * frame.width, frame.minY + 0.32353 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.64138 * frame.width, frame.minY + 0.31379 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.65670 * frame.width, frame.minY + 0.31379 * frame.height))
            clickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.66615 * frame.width, frame.minY + 0.35878 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.67560 * frame.width, frame.minY + 0.33326 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.67560 * frame.width, frame.minY + 0.34905 * frame.height))
            clickedCrossPath.closePath()
            color.setFill()
            clickedCrossPath.fill()
        }


        if (notClicked) {
            //// notClickedCross Drawing
            var notClickedCrossPath = UIBezierPath()
            notClickedCrossPath.moveToPoint(CGPointMake(frame.minX + 0.49477 * frame.width, frame.minY + 0.05111 * frame.height))
            notClickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.93015 * frame.width, frame.minY + 0.49931 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.73484 * frame.width, frame.minY + 0.05111 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.93015 * frame.width, frame.minY + 0.25217 * frame.height))
            notClickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.49477 * frame.width, frame.minY + 0.94851 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.93015 * frame.width, frame.minY + 0.74645 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.73484 * frame.width, frame.minY + 0.94851 * frame.height))
            notClickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.28500 * frame.width, frame.minY + 0.89274 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.41877 * frame.width, frame.minY + 0.94851 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.34725 * frame.width, frame.minY + 0.92826 * frame.height))
            notClickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.05938 * frame.width, frame.minY + 0.49931 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.15061 * frame.width, frame.minY + 0.81606 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.05938 * frame.width, frame.minY + 0.66821 * frame.height))
            notClickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.49477 * frame.width, frame.minY + 0.05111 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.05938 * frame.width, frame.minY + 0.25217 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.25469 * frame.width, frame.minY + 0.05111 * frame.height))
            notClickedCrossPath.closePath()
            notClickedCrossPath.moveToPoint(CGPointMake(frame.minX + 0.49475 * frame.width, frame.minY + 0.00087 * frame.height))
            notClickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.01063 * frame.width, frame.minY + 0.49969 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.22738 * frame.width, frame.minY + 0.00087 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.01063 * frame.width, frame.minY + 0.22421 * frame.height))
            notClickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.49475 * frame.width, frame.minY + 0.99849 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.01063 * frame.width, frame.minY + 0.77518 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.22738 * frame.width, frame.minY + 0.99849 * frame.height))
            notClickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.97888 * frame.width, frame.minY + 0.49969 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.76214 * frame.width, frame.minY + 0.99849 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.97888 * frame.width, frame.minY + 0.77518 * frame.height))
            notClickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.49475 * frame.width, frame.minY + 0.00087 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.97888 * frame.width, frame.minY + 0.22421 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.76214 * frame.width, frame.minY + 0.00087 * frame.height))
            notClickedCrossPath.addLineToPoint(CGPointMake(frame.minX + 0.49475 * frame.width, frame.minY + 0.00087 * frame.height))
            notClickedCrossPath.closePath()
            notClickedCrossPath.moveToPoint(CGPointMake(frame.minX + 0.35816 * frame.width, frame.minY + 0.32352 * frame.height))
            notClickedCrossPath.addLineToPoint(CGPointMake(frame.minX + 0.66615 * frame.width, frame.minY + 0.64086 * frame.height))
            notClickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.66615 * frame.width, frame.minY + 0.67612 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.67560 * frame.width, frame.minY + 0.65059 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.67560 * frame.width, frame.minY + 0.66638 * frame.height))
            notClickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.63193 * frame.width, frame.minY + 0.67612 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.65670 * frame.width, frame.minY + 0.68586 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.64138 * frame.width, frame.minY + 0.68585 * frame.height))
            notClickedCrossPath.addLineToPoint(CGPointMake(frame.minX + 0.32394 * frame.width, frame.minY + 0.35878 * frame.height))
            notClickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.32393 * frame.width, frame.minY + 0.32353 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.31449 * frame.width, frame.minY + 0.34904 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.31448 * frame.width, frame.minY + 0.33326 * frame.height))
            notClickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.35816 * frame.width, frame.minY + 0.32352 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.33338 * frame.width, frame.minY + 0.31379 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.34871 * frame.width, frame.minY + 0.31379 * frame.height))
            notClickedCrossPath.closePath()
            notClickedCrossPath.moveToPoint(CGPointMake(frame.minX + 0.66615 * frame.width, frame.minY + 0.35878 * frame.height))
            notClickedCrossPath.addLineToPoint(CGPointMake(frame.minX + 0.35816 * frame.width, frame.minY + 0.67612 * frame.height))
            notClickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.32394 * frame.width, frame.minY + 0.67612 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.34870 * frame.width, frame.minY + 0.68586 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.33339 * frame.width, frame.minY + 0.68586 * frame.height))
            notClickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.32393 * frame.width, frame.minY + 0.64086 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.31448 * frame.width, frame.minY + 0.66638 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.31448 * frame.width, frame.minY + 0.65060 * frame.height))
            notClickedCrossPath.addLineToPoint(CGPointMake(frame.minX + 0.63193 * frame.width, frame.minY + 0.32352 * frame.height))
            notClickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.66615 * frame.width, frame.minY + 0.32353 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.64138 * frame.width, frame.minY + 0.31379 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.65670 * frame.width, frame.minY + 0.31379 * frame.height))
            notClickedCrossPath.addCurveToPoint(CGPointMake(frame.minX + 0.66615 * frame.width, frame.minY + 0.35878 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.67560 * frame.width, frame.minY + 0.33326 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.67560 * frame.width, frame.minY + 0.34905 * frame.height))
            notClickedCrossPath.closePath()
            plusIconCopyColor.setFill()
            notClickedCrossPath.fill()
        }
    }

}
