//
//  PlusSK.swift
//  Weshapp
//
//  Created by SM on 24/03/2015.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class PlusSK : NSObject {

    //// Drawing Methods

    public class func drawPlusCanvas(#frame: CGRect, notClicked: Bool, clicked: Bool) {
        //// Color Declarations
        let plusIconCopyColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let color = UIColor(red: 0.647, green: 0.878, blue: 0.914, alpha: 1.000)

        if (notClicked) {
            //// notClickedPlus Drawing
            var notClickedPlusPath = UIBezierPath()
            notClickedPlusPath.moveToPoint(CGPointMake(frame.minX + 0.81796 * frame.width, frame.minY + 0.18206 * frame.height))
            notClickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.81823 * frame.width, frame.minY + 0.81770 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.99328 * frame.width, frame.minY + 0.35739 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.99341 * frame.width, frame.minY + 0.64253 * frame.height))
            notClickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.18189 * frame.width, frame.minY + 0.81813 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.64306 * frame.width, frame.minY + 0.99287 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.35721 * frame.width, frame.minY + 0.99346 * frame.height))
            notClickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.18232 * frame.width, frame.minY + 0.18178 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.00656 * frame.width, frame.minY + 0.64281 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.00715 * frame.width, frame.minY + 0.35696 * frame.height))
            notClickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.81796 * frame.width, frame.minY + 0.18206 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.35749 * frame.width, frame.minY + 0.00661 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.64263 * frame.width, frame.minY + 0.00674 * frame.height))
            notClickedPlusPath.closePath()
            notClickedPlusPath.moveToPoint(CGPointMake(frame.minX + 0.85355 * frame.width, frame.minY + 0.14644 * frame.height))
            notClickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.14645 * frame.width, frame.minY + 0.14645 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.65829 * frame.width, frame.minY + -0.04882 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.34171 * frame.width, frame.minY + -0.04881 * frame.height))
            notClickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.14645 * frame.width, frame.minY + 0.85355 * frame.height), controlPoint1: CGPointMake(frame.minX + -0.04882 * frame.width, frame.minY + 0.34171 * frame.height), controlPoint2: CGPointMake(frame.minX + -0.04881 * frame.width, frame.minY + 0.65829 * frame.height))
            notClickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.85355 * frame.width, frame.minY + 0.85355 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.34172 * frame.width, frame.minY + 1.04882 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.65828 * frame.width, frame.minY + 1.04882 * frame.height))
            notClickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.85355 * frame.width, frame.minY + 0.14644 * frame.height), controlPoint1: CGPointMake(frame.minX + 1.04881 * frame.width, frame.minY + 0.65829 * frame.height), controlPoint2: CGPointMake(frame.minX + 1.04882 * frame.width, frame.minY + 0.34171 * frame.height))
            notClickedPlusPath.addLineToPoint(CGPointMake(frame.minX + 0.85355 * frame.width, frame.minY + 0.14644 * frame.height))
            notClickedPlusPath.closePath()
            notClickedPlusPath.moveToPoint(CGPointMake(frame.minX + 0.52511 * frame.width, frame.minY + 0.27538 * frame.height))
            notClickedPlusPath.addLineToPoint(CGPointMake(frame.minX + 0.52511 * frame.width, frame.minY + 0.72523 * frame.height))
            notClickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.50011 * frame.width, frame.minY + 0.75022 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.52511 * frame.width, frame.minY + 0.73903 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.51392 * frame.width, frame.minY + 0.75022 * frame.height))
            notClickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.47513 * frame.width, frame.minY + 0.72523 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.48631 * frame.width, frame.minY + 0.75022 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.47513 * frame.width, frame.minY + 0.73903 * frame.height))
            notClickedPlusPath.addLineToPoint(CGPointMake(frame.minX + 0.47513 * frame.width, frame.minY + 0.27538 * frame.height))
            notClickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.50011 * frame.width, frame.minY + 0.25039 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.47513 * frame.width, frame.minY + 0.26158 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.48631 * frame.width, frame.minY + 0.25039 * frame.height))
            notClickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.52511 * frame.width, frame.minY + 0.27538 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.51391 * frame.width, frame.minY + 0.25039 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.52511 * frame.width, frame.minY + 0.26158 * frame.height))
            notClickedPlusPath.closePath()
            notClickedPlusPath.moveToPoint(CGPointMake(frame.minX + 0.72504 * frame.width, frame.minY + 0.52529 * frame.height))
            notClickedPlusPath.addLineToPoint(CGPointMake(frame.minX + 0.27519 * frame.width, frame.minY + 0.52529 * frame.height))
            notClickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.25020 * frame.width, frame.minY + 0.50031 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.26138 * frame.width, frame.minY + 0.52529 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.25020 * frame.width, frame.minY + 0.51411 * frame.height))
            notClickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.27519 * frame.width, frame.minY + 0.47531 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.25020 * frame.width, frame.minY + 0.48650 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.26138 * frame.width, frame.minY + 0.47531 * frame.height))
            notClickedPlusPath.addLineToPoint(CGPointMake(frame.minX + 0.72504 * frame.width, frame.minY + 0.47531 * frame.height))
            notClickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.75003 * frame.width, frame.minY + 0.50031 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.73884 * frame.width, frame.minY + 0.47531 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.75003 * frame.width, frame.minY + 0.48650 * frame.height))
            notClickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.72504 * frame.width, frame.minY + 0.52529 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.75003 * frame.width, frame.minY + 0.51411 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.73884 * frame.width, frame.minY + 0.52529 * frame.height))
            notClickedPlusPath.closePath()
            plusIconCopyColor.setFill()
            notClickedPlusPath.fill()
        }


        if (clicked) {
            //// clickedPlus Drawing
            var clickedPlusPath = UIBezierPath()
            clickedPlusPath.moveToPoint(CGPointMake(frame.minX + 0.81796 * frame.width, frame.minY + 0.18206 * frame.height))
            clickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.81823 * frame.width, frame.minY + 0.81770 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.99328 * frame.width, frame.minY + 0.35739 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.99341 * frame.width, frame.minY + 0.64253 * frame.height))
            clickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.18189 * frame.width, frame.minY + 0.81813 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.64306 * frame.width, frame.minY + 0.99287 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.35721 * frame.width, frame.minY + 0.99346 * frame.height))
            clickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.18232 * frame.width, frame.minY + 0.18178 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.00656 * frame.width, frame.minY + 0.64281 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.00715 * frame.width, frame.minY + 0.35696 * frame.height))
            clickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.81796 * frame.width, frame.minY + 0.18206 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.35749 * frame.width, frame.minY + 0.00661 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.64263 * frame.width, frame.minY + 0.00674 * frame.height))
            clickedPlusPath.closePath()
            clickedPlusPath.moveToPoint(CGPointMake(frame.minX + 0.85355 * frame.width, frame.minY + 0.14644 * frame.height))
            clickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.14645 * frame.width, frame.minY + 0.14645 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.65829 * frame.width, frame.minY + -0.04882 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.34171 * frame.width, frame.minY + -0.04881 * frame.height))
            clickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.14645 * frame.width, frame.minY + 0.85355 * frame.height), controlPoint1: CGPointMake(frame.minX + -0.04882 * frame.width, frame.minY + 0.34171 * frame.height), controlPoint2: CGPointMake(frame.minX + -0.04881 * frame.width, frame.minY + 0.65829 * frame.height))
            clickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.85355 * frame.width, frame.minY + 0.85355 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.34172 * frame.width, frame.minY + 1.04882 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.65828 * frame.width, frame.minY + 1.04882 * frame.height))
            clickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.85355 * frame.width, frame.minY + 0.14644 * frame.height), controlPoint1: CGPointMake(frame.minX + 1.04881 * frame.width, frame.minY + 0.65829 * frame.height), controlPoint2: CGPointMake(frame.minX + 1.04882 * frame.width, frame.minY + 0.34171 * frame.height))
            clickedPlusPath.addLineToPoint(CGPointMake(frame.minX + 0.85355 * frame.width, frame.minY + 0.14644 * frame.height))
            clickedPlusPath.closePath()
            clickedPlusPath.moveToPoint(CGPointMake(frame.minX + 0.52511 * frame.width, frame.minY + 0.27538 * frame.height))
            clickedPlusPath.addLineToPoint(CGPointMake(frame.minX + 0.52511 * frame.width, frame.minY + 0.72523 * frame.height))
            clickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.50011 * frame.width, frame.minY + 0.75022 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.52511 * frame.width, frame.minY + 0.73903 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.51392 * frame.width, frame.minY + 0.75022 * frame.height))
            clickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.47513 * frame.width, frame.minY + 0.72523 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.48631 * frame.width, frame.minY + 0.75022 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.47513 * frame.width, frame.minY + 0.73903 * frame.height))
            clickedPlusPath.addLineToPoint(CGPointMake(frame.minX + 0.47513 * frame.width, frame.minY + 0.27538 * frame.height))
            clickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.50011 * frame.width, frame.minY + 0.25039 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.47513 * frame.width, frame.minY + 0.26158 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.48631 * frame.width, frame.minY + 0.25039 * frame.height))
            clickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.52511 * frame.width, frame.minY + 0.27538 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.51391 * frame.width, frame.minY + 0.25039 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.52511 * frame.width, frame.minY + 0.26158 * frame.height))
            clickedPlusPath.closePath()
            clickedPlusPath.moveToPoint(CGPointMake(frame.minX + 0.72504 * frame.width, frame.minY + 0.52529 * frame.height))
            clickedPlusPath.addLineToPoint(CGPointMake(frame.minX + 0.27519 * frame.width, frame.minY + 0.52529 * frame.height))
            clickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.25020 * frame.width, frame.minY + 0.50031 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.26138 * frame.width, frame.minY + 0.52529 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.25020 * frame.width, frame.minY + 0.51411 * frame.height))
            clickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.27519 * frame.width, frame.minY + 0.47531 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.25020 * frame.width, frame.minY + 0.48650 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.26138 * frame.width, frame.minY + 0.47531 * frame.height))
            clickedPlusPath.addLineToPoint(CGPointMake(frame.minX + 0.72504 * frame.width, frame.minY + 0.47531 * frame.height))
            clickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.75003 * frame.width, frame.minY + 0.50031 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.73884 * frame.width, frame.minY + 0.47531 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.75003 * frame.width, frame.minY + 0.48650 * frame.height))
            clickedPlusPath.addCurveToPoint(CGPointMake(frame.minX + 0.72504 * frame.width, frame.minY + 0.52529 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.75003 * frame.width, frame.minY + 0.51411 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.73884 * frame.width, frame.minY + 0.52529 * frame.height))
            clickedPlusPath.closePath()
            color.setFill()
            clickedPlusPath.fill()
        }
    }

}
