//
//  WClockIconSK.swift
//  Weshapp
//
//  Created by SM on 02/04/2015.
//  Copyright (c) 2015 Weshapp. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class WClockIconSK : NSObject {

    //// Drawing Methods

    public class func drawClock(#frame: CGRect, clockInactive: Bool, clockActive: Bool) {
        //// Color Declarations
        let clockActiveColor = UIColor(red: 0.294, green: 0.757, blue: 0.824, alpha: 1.000)
        let clockInactiveColor = UIColor(red: 0.733, green: 0.733, blue: 0.733, alpha: 1.000)

        if (clockActive) {
            //// clockIconActive Drawing
            var clockIconActivePath = UIBezierPath()
            clockIconActivePath.moveToPoint(CGPointMake(frame.minX + 0.49264 * frame.width, frame.minY + 0.07483 * frame.height))
            clockIconActivePath.addCurveToPoint(CGPointMake(frame.minX + 0.91040 * frame.width, frame.minY + 0.49231 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.72299 * frame.width, frame.minY + 0.07483 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.91040 * frame.width, frame.minY + 0.26211 * frame.height))
            clockIconActivePath.addCurveToPoint(CGPointMake(frame.minX + 0.49264 * frame.width, frame.minY + 0.91071 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.91040 * frame.width, frame.minY + 0.72250 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.72299 * frame.width, frame.minY + 0.91071 * frame.height))
            clockIconActivePath.addCurveToPoint(CGPointMake(frame.minX + 0.07489 * frame.width, frame.minY + 0.49231 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.26228 * frame.width, frame.minY + 0.91071 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.07489 * frame.width, frame.minY + 0.72250 * frame.height))
            clockIconActivePath.addCurveToPoint(CGPointMake(frame.minX + 0.49264 * frame.width, frame.minY + 0.07483 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.07489 * frame.width, frame.minY + 0.26211 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.26228 * frame.width, frame.minY + 0.07483 * frame.height))
            clockIconActivePath.closePath()
            clockIconActivePath.moveToPoint(CGPointMake(frame.minX + 0.49263 * frame.width, frame.minY + 0.00000 * frame.height))
            clockIconActivePath.addCurveToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.49229 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.22055 * frame.width, frame.minY + 0.00000 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.22041 * frame.height))
            clockIconActivePath.addCurveToPoint(CGPointMake(frame.minX + 0.49263 * frame.width, frame.minY + 0.98459 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.76419 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.22055 * frame.width, frame.minY + 0.98459 * frame.height))
            clockIconActivePath.addCurveToPoint(CGPointMake(frame.minX + 0.98526 * frame.width, frame.minY + 0.49229 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.76471 * frame.width, frame.minY + 0.98459 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.98526 * frame.width, frame.minY + 0.76419 * frame.height))
            clockIconActivePath.addCurveToPoint(CGPointMake(frame.minX + 0.49263 * frame.width, frame.minY + 0.00000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.98526 * frame.width, frame.minY + 0.22041 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.76471 * frame.width, frame.minY + 0.00000 * frame.height))
            clockIconActivePath.addLineToPoint(CGPointMake(frame.minX + 0.49263 * frame.width, frame.minY + 0.00000 * frame.height))
            clockIconActivePath.closePath()
            clockIconActivePath.moveToPoint(CGPointMake(frame.minX + 0.49418 * frame.width, frame.minY + 0.17136 * frame.height))
            clockIconActivePath.addCurveToPoint(CGPointMake(frame.minX + 0.52349 * frame.width, frame.minY + 0.20249 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.51036 * frame.width, frame.minY + 0.17136 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.52349 * frame.width, frame.minY + 0.18530 * frame.height))
            clockIconActivePath.addLineToPoint(CGPointMake(frame.minX + 0.52349 * frame.width, frame.minY + 0.51380 * frame.height))
            clockIconActivePath.addCurveToPoint(CGPointMake(frame.minX + 0.49418 * frame.width, frame.minY + 0.54494 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.52349 * frame.width, frame.minY + 0.53100 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.51036 * frame.width, frame.minY + 0.54494 * frame.height))
            clockIconActivePath.addCurveToPoint(CGPointMake(frame.minX + 0.46486 * frame.width, frame.minY + 0.51380 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.47797 * frame.width, frame.minY + 0.54494 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.46486 * frame.width, frame.minY + 0.53100 * frame.height))
            clockIconActivePath.addLineToPoint(CGPointMake(frame.minX + 0.46486 * frame.width, frame.minY + 0.20249 * frame.height))
            clockIconActivePath.addCurveToPoint(CGPointMake(frame.minX + 0.49418 * frame.width, frame.minY + 0.17136 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.46486 * frame.width, frame.minY + 0.18530 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.47797 * frame.width, frame.minY + 0.17136 * frame.height))
            clockIconActivePath.closePath()
            clockIconActivePath.moveToPoint(CGPointMake(frame.minX + 0.67665 * frame.width, frame.minY + 0.69258 * frame.height))
            clockIconActivePath.addCurveToPoint(CGPointMake(frame.minX + 0.63061 * frame.width, frame.minY + 0.69258 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.66394 * frame.width, frame.minY + 0.70529 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.64332 * frame.width, frame.minY + 0.70529 * frame.height))
            clockIconActivePath.addLineToPoint(CGPointMake(frame.minX + 0.46947 * frame.width, frame.minY + 0.53156 * frame.height))
            clockIconActivePath.addCurveToPoint(CGPointMake(frame.minX + 0.46947 * frame.width, frame.minY + 0.48555 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.45675 * frame.width, frame.minY + 0.51885 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.45675 * frame.width, frame.minY + 0.49824 * frame.height))
            clockIconActivePath.addCurveToPoint(CGPointMake(frame.minX + 0.51551 * frame.width, frame.minY + 0.48555 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.48218 * frame.width, frame.minY + 0.47283 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.50278 * frame.width, frame.minY + 0.47283 * frame.height))
            clockIconActivePath.addLineToPoint(CGPointMake(frame.minX + 0.67665 * frame.width, frame.minY + 0.64658 * frame.height))
            clockIconActivePath.addCurveToPoint(CGPointMake(frame.minX + 0.67665 * frame.width, frame.minY + 0.69258 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.68936 * frame.width, frame.minY + 0.65928 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.68936 * frame.width, frame.minY + 0.67988 * frame.height))
            clockIconActivePath.closePath()
            clockActiveColor.setFill()
            clockIconActivePath.fill()
        }


        if (clockInactive) {
            //// clockIconInactive Drawing
            var clockIconInactivePath = UIBezierPath()
            clockIconInactivePath.moveToPoint(CGPointMake(frame.minX + 0.49264 * frame.width, frame.minY + 0.07484 * frame.height))
            clockIconInactivePath.addCurveToPoint(CGPointMake(frame.minX + 0.91040 * frame.width, frame.minY + 0.49231 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.72299 * frame.width, frame.minY + 0.07484 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.91040 * frame.width, frame.minY + 0.26211 * frame.height))
            clockIconInactivePath.addCurveToPoint(CGPointMake(frame.minX + 0.49264 * frame.width, frame.minY + 0.91072 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.91040 * frame.width, frame.minY + 0.72251 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.72299 * frame.width, frame.minY + 0.91072 * frame.height))
            clockIconInactivePath.addCurveToPoint(CGPointMake(frame.minX + 0.07489 * frame.width, frame.minY + 0.49231 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.26228 * frame.width, frame.minY + 0.91072 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.07489 * frame.width, frame.minY + 0.72251 * frame.height))
            clockIconInactivePath.addCurveToPoint(CGPointMake(frame.minX + 0.49264 * frame.width, frame.minY + 0.07484 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.07489 * frame.width, frame.minY + 0.26211 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.26228 * frame.width, frame.minY + 0.07484 * frame.height))
            clockIconInactivePath.closePath()
            clockIconInactivePath.moveToPoint(CGPointMake(frame.minX + 0.49263 * frame.width, frame.minY + 0.00000 * frame.height))
            clockIconInactivePath.addCurveToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.49229 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.22055 * frame.width, frame.minY + 0.00000 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.22041 * frame.height))
            clockIconInactivePath.addCurveToPoint(CGPointMake(frame.minX + 0.49263 * frame.width, frame.minY + 0.98459 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.76419 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.22055 * frame.width, frame.minY + 0.98459 * frame.height))
            clockIconInactivePath.addCurveToPoint(CGPointMake(frame.minX + 0.98526 * frame.width, frame.minY + 0.49229 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.76471 * frame.width, frame.minY + 0.98459 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.98526 * frame.width, frame.minY + 0.76419 * frame.height))
            clockIconInactivePath.addCurveToPoint(CGPointMake(frame.minX + 0.49263 * frame.width, frame.minY + 0.00000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.98526 * frame.width, frame.minY + 0.22041 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.76471 * frame.width, frame.minY + 0.00000 * frame.height))
            clockIconInactivePath.addLineToPoint(CGPointMake(frame.minX + 0.49263 * frame.width, frame.minY + 0.00000 * frame.height))
            clockIconInactivePath.closePath()
            clockIconInactivePath.moveToPoint(CGPointMake(frame.minX + 0.49418 * frame.width, frame.minY + 0.17136 * frame.height))
            clockIconInactivePath.addCurveToPoint(CGPointMake(frame.minX + 0.52349 * frame.width, frame.minY + 0.20250 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.51036 * frame.width, frame.minY + 0.17136 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.52349 * frame.width, frame.minY + 0.18530 * frame.height))
            clockIconInactivePath.addLineToPoint(CGPointMake(frame.minX + 0.52349 * frame.width, frame.minY + 0.51381 * frame.height))
            clockIconInactivePath.addCurveToPoint(CGPointMake(frame.minX + 0.49418 * frame.width, frame.minY + 0.54494 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.52349 * frame.width, frame.minY + 0.53100 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.51036 * frame.width, frame.minY + 0.54494 * frame.height))
            clockIconInactivePath.addCurveToPoint(CGPointMake(frame.minX + 0.46486 * frame.width, frame.minY + 0.51381 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.47797 * frame.width, frame.minY + 0.54494 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.46486 * frame.width, frame.minY + 0.53100 * frame.height))
            clockIconInactivePath.addLineToPoint(CGPointMake(frame.minX + 0.46486 * frame.width, frame.minY + 0.20250 * frame.height))
            clockIconInactivePath.addCurveToPoint(CGPointMake(frame.minX + 0.49418 * frame.width, frame.minY + 0.17136 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.46486 * frame.width, frame.minY + 0.18530 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.47797 * frame.width, frame.minY + 0.17136 * frame.height))
            clockIconInactivePath.closePath()
            clockIconInactivePath.moveToPoint(CGPointMake(frame.minX + 0.67665 * frame.width, frame.minY + 0.69259 * frame.height))
            clockIconInactivePath.addCurveToPoint(CGPointMake(frame.minX + 0.63061 * frame.width, frame.minY + 0.69259 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.66394 * frame.width, frame.minY + 0.70529 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.64332 * frame.width, frame.minY + 0.70529 * frame.height))
            clockIconInactivePath.addLineToPoint(CGPointMake(frame.minX + 0.46947 * frame.width, frame.minY + 0.53156 * frame.height))
            clockIconInactivePath.addCurveToPoint(CGPointMake(frame.minX + 0.46947 * frame.width, frame.minY + 0.48555 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.45675 * frame.width, frame.minY + 0.51885 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.45675 * frame.width, frame.minY + 0.49825 * frame.height))
            clockIconInactivePath.addCurveToPoint(CGPointMake(frame.minX + 0.51551 * frame.width, frame.minY + 0.48555 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.48218 * frame.width, frame.minY + 0.47283 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.50278 * frame.width, frame.minY + 0.47283 * frame.height))
            clockIconInactivePath.addLineToPoint(CGPointMake(frame.minX + 0.67665 * frame.width, frame.minY + 0.64658 * frame.height))
            clockIconInactivePath.addCurveToPoint(CGPointMake(frame.minX + 0.67665 * frame.width, frame.minY + 0.69259 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.68936 * frame.width, frame.minY + 0.65928 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.68936 * frame.width, frame.minY + 0.67988 * frame.height))
            clockIconInactivePath.closePath()
            clockInactiveColor.setFill()
            clockIconInactivePath.fill()
        }
    }

}
