//
//  WDeleteSK.swift
//  Weshapp
//
//  Created by SM on 07/04/2015.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class WDeleteSK : NSObject {

    //// Drawing Methods

    public class func drawDeleteChannelBtnCanvas(#frame: CGRect, deleteBtnClicked: Bool, deleteBtnNotClicked: Bool) {
        //// Color Declarations
        let red = UIColor(red: 1.000, green: 0.439, blue: 0.439, alpha: 1.000)
        let shape3StrokeColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let iconClickedColor = UIColor(red: 1.000, green: 0.788, blue: 0.788, alpha: 1.000)
        let btnClickedColor = UIColor(red: 0.890, green: 0.290, blue: 0.290, alpha: 1.000)
        let shape5CopyColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let shape5CopyStrokeColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)


        //// Subframes
        let deletChannelBtnNotClicked: CGRect = CGRectMake(frame.minX + floor(frame.width * 0.00000 + 0.5), frame.minY + floor(frame.height * 0.00000 + 0.5), floor(frame.width * 1.00000 + 0.5) - floor(frame.width * 0.00000 + 0.5), floor(frame.height * 1.00000 + 0.5) - floor(frame.height * 0.00000 + 0.5))
        let deletChannelBtnClicked: CGRect = CGRectMake(frame.minX + floor(frame.width * 0.00000 + 0.5), frame.minY + floor(frame.height * 0.00000 + 0.5), floor(frame.width * 1.00000 + 0.5) - floor(frame.width * 0.00000 + 0.5), floor(frame.height * 1.00000 + 0.5) - floor(frame.height * 0.00000 + 0.5))


        if (deleteBtnNotClicked) {
            //// deletChannelBtnNotClicked
            //// Rectangle Drawing
            let rectanglePath = UIBezierPath(rect: CGRectMake(deletChannelBtnNotClicked.minX + floor(deletChannelBtnNotClicked.width * 0.00000 + 0.5), deletChannelBtnNotClicked.minY + floor(deletChannelBtnNotClicked.height * 0.00000 + 0.5), floor(deletChannelBtnNotClicked.width * 1.00000 + 0.5) - floor(deletChannelBtnNotClicked.width * 0.00000 + 0.5), floor(deletChannelBtnNotClicked.height * 1.00000 + 0.5) - floor(deletChannelBtnNotClicked.height * 0.00000 + 0.5)))
            red.setFill()
            rectanglePath.fill()
            shape3StrokeColor.setStroke()
            rectanglePath.lineWidth = 0.25
            rectanglePath.stroke()


            //// Shape 5 copy Drawing
            var shape5CopyPath = UIBezierPath()
            shape5CopyPath.moveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.50001 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.67901 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addCurveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.32099 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.49999 * deletChannelBtnNotClicked.height), controlPoint1: CGPointMake(deletChannelBtnNotClicked.minX + 0.40131 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.67901 * deletChannelBtnNotClicked.height), controlPoint2: CGPointMake(deletChannelBtnNotClicked.minX + 0.32099 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.59872 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addCurveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.50001 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.32099 * deletChannelBtnNotClicked.height), controlPoint1: CGPointMake(deletChannelBtnNotClicked.minX + 0.32099 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.40129 * deletChannelBtnNotClicked.height), controlPoint2: CGPointMake(deletChannelBtnNotClicked.minX + 0.40131 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.32099 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addCurveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.67901 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.49999 * deletChannelBtnNotClicked.height), controlPoint1: CGPointMake(deletChannelBtnNotClicked.minX + 0.59872 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.32099 * deletChannelBtnNotClicked.height), controlPoint2: CGPointMake(deletChannelBtnNotClicked.minX + 0.67901 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.40129 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addCurveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.50001 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.67901 * deletChannelBtnNotClicked.height), controlPoint1: CGPointMake(deletChannelBtnNotClicked.minX + 0.67901 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.59872 * deletChannelBtnNotClicked.height), controlPoint2: CGPointMake(deletChannelBtnNotClicked.minX + 0.59872 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.67901 * deletChannelBtnNotClicked.height))
            shape5CopyPath.closePath()
            shape5CopyPath.moveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.50001 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.32653 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addCurveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.32654 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.49999 * deletChannelBtnNotClicked.height), controlPoint1: CGPointMake(deletChannelBtnNotClicked.minX + 0.40437 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.32653 * deletChannelBtnNotClicked.height), controlPoint2: CGPointMake(deletChannelBtnNotClicked.minX + 0.32654 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.40434 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addCurveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.50001 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.67347 * deletChannelBtnNotClicked.height), controlPoint1: CGPointMake(deletChannelBtnNotClicked.minX + 0.32654 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.59565 * deletChannelBtnNotClicked.height), controlPoint2: CGPointMake(deletChannelBtnNotClicked.minX + 0.40437 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.67347 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addCurveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.67347 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.49999 * deletChannelBtnNotClicked.height), controlPoint1: CGPointMake(deletChannelBtnNotClicked.minX + 0.59566 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.67347 * deletChannelBtnNotClicked.height), controlPoint2: CGPointMake(deletChannelBtnNotClicked.minX + 0.67347 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.59565 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addCurveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.50001 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.32653 * deletChannelBtnNotClicked.height), controlPoint1: CGPointMake(deletChannelBtnNotClicked.minX + 0.67347 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.40434 * deletChannelBtnNotClicked.height), controlPoint2: CGPointMake(deletChannelBtnNotClicked.minX + 0.59566 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.32653 * deletChannelBtnNotClicked.height))
            shape5CopyPath.closePath()
            shape5CopyPath.moveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.53904 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.57516 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.46097 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.57516 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addCurveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.45441 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.56847 * deletChannelBtnNotClicked.height), controlPoint1: CGPointMake(deletChannelBtnNotClicked.minX + 0.45759 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.57516 * deletChannelBtnNotClicked.height), controlPoint2: CGPointMake(deletChannelBtnNotClicked.minX + 0.45469 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.57222 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.44756 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.47875 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.55245 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.47875 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.54559 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.56847 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addCurveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.53904 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.57516 * deletChannelBtnNotClicked.height), controlPoint1: CGPointMake(deletChannelBtnNotClicked.minX + 0.54533 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.57222 * deletChannelBtnNotClicked.height), controlPoint2: CGPointMake(deletChannelBtnNotClicked.minX + 0.54246 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.57516 * deletChannelBtnNotClicked.height))
            shape5CopyPath.closePath()
            shape5CopyPath.moveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.45354 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.48430 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.45994 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.56805 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addCurveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.46097 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.56963 * deletChannelBtnNotClicked.height), controlPoint1: CGPointMake(deletChannelBtnNotClicked.minX + 0.46002 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.56901 * deletChannelBtnNotClicked.height), controlPoint2: CGPointMake(deletChannelBtnNotClicked.minX + 0.46066 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.56963 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.53904 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.56963 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addCurveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.54007 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.56806 * deletChannelBtnNotClicked.height), controlPoint1: CGPointMake(deletChannelBtnNotClicked.minX + 0.53936 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.56963 * deletChannelBtnNotClicked.height), controlPoint2: CGPointMake(deletChannelBtnNotClicked.minX + 0.54000 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.56901 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.54647 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.48430 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.45354 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.48430 * deletChannelBtnNotClicked.height))
            shape5CopyPath.closePath()
            shape5CopyPath.moveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.55497 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.47408 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.44504 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.47408 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.44504 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.45432 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addCurveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.45822 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.44043 * deletChannelBtnNotClicked.height), controlPoint1: CGPointMake(deletChannelBtnNotClicked.minX + 0.44504 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.44667 * deletChannelBtnNotClicked.height), controlPoint2: CGPointMake(deletChannelBtnNotClicked.minX + 0.45094 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.44043 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.54179 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.44043 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addCurveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.55497 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.45432 * deletChannelBtnNotClicked.height), controlPoint1: CGPointMake(deletChannelBtnNotClicked.minX + 0.54906 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.44043 * deletChannelBtnNotClicked.height), controlPoint2: CGPointMake(deletChannelBtnNotClicked.minX + 0.55497 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.44667 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.55497 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.47408 * deletChannelBtnNotClicked.height))
            shape5CopyPath.closePath()
            shape5CopyPath.moveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.45057 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.46854 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.54943 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.46854 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.54943 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.45432 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addCurveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.54179 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.44598 * deletChannelBtnNotClicked.height), controlPoint1: CGPointMake(deletChannelBtnNotClicked.minX + 0.54943 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.44972 * deletChannelBtnNotClicked.height), controlPoint2: CGPointMake(deletChannelBtnNotClicked.minX + 0.54600 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.44598 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.45822 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.44598 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addCurveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.45057 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.45432 * deletChannelBtnNotClicked.height), controlPoint1: CGPointMake(deletChannelBtnNotClicked.minX + 0.45401 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.44598 * deletChannelBtnNotClicked.height), controlPoint2: CGPointMake(deletChannelBtnNotClicked.minX + 0.45057 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.44972 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.45057 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.46854 * deletChannelBtnNotClicked.height))
            shape5CopyPath.closePath()
            shape5CopyPath.moveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.47687 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.43799 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addCurveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.47687 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.43143 * deletChannelBtnNotClicked.height), controlPoint1: CGPointMake(deletChannelBtnNotClicked.minX + 0.47687 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.43799 * deletChannelBtnNotClicked.height), controlPoint2: CGPointMake(deletChannelBtnNotClicked.minX + 0.47687 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.43505 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addCurveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.48381 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.42482 * deletChannelBtnNotClicked.height), controlPoint1: CGPointMake(deletChannelBtnNotClicked.minX + 0.47687 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.42778 * deletChannelBtnNotClicked.height), controlPoint2: CGPointMake(deletChannelBtnNotClicked.minX + 0.47998 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.42482 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.51620 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.42482 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addCurveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.52315 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.43143 * deletChannelBtnNotClicked.height), controlPoint1: CGPointMake(deletChannelBtnNotClicked.minX + 0.52004 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.42482 * deletChannelBtnNotClicked.height), controlPoint2: CGPointMake(deletChannelBtnNotClicked.minX + 0.52315 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.42778 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.52315 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.43799 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.47687 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.43799 * deletChannelBtnNotClicked.height))
            shape5CopyPath.closePath()
            shape5CopyPath.moveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.49417 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.54804 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.48584 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.54804 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.48584 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.48981 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.49417 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.48981 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.49417 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.54804 * deletChannelBtnNotClicked.height))
            shape5CopyPath.closePath()
            shape5CopyPath.moveToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.51416 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.54804 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.50584 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.54804 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.50584 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.48981 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.51416 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.48981 * deletChannelBtnNotClicked.height))
            shape5CopyPath.addLineToPoint(CGPointMake(deletChannelBtnNotClicked.minX + 0.51416 * deletChannelBtnNotClicked.width, deletChannelBtnNotClicked.minY + 0.54804 * deletChannelBtnNotClicked.height))
            shape5CopyPath.closePath()
            shape5CopyPath.miterLimit = 100;

            shape5CopyPath.lineCapStyle = kCGLineCapRound;

            shape5CopyPath.lineJoinStyle = kCGLineJoinRound;

            shape5CopyColor.setFill()
            shape5CopyPath.fill()
            shape5CopyStrokeColor.setStroke()
            shape5CopyPath.lineWidth = 0.5
            shape5CopyPath.stroke()


        }


        if (deleteBtnClicked) {
            //// deletChannelBtnClicked
            //// Rectangle 2 Drawing
            let rectangle2Path = UIBezierPath(rect: CGRectMake(deletChannelBtnClicked.minX + floor(deletChannelBtnClicked.width * 0.00000 + 0.5), deletChannelBtnClicked.minY + floor(deletChannelBtnClicked.height * 0.00000 + 0.5), floor(deletChannelBtnClicked.width * 1.00000 + 0.5) - floor(deletChannelBtnClicked.width * 0.00000 + 0.5), floor(deletChannelBtnClicked.height * 1.00000 + 0.5) - floor(deletChannelBtnClicked.height * 0.00000 + 0.5)))
            btnClickedColor.setFill()
            rectangle2Path.fill()
            shape3StrokeColor.setStroke()
            rectangle2Path.lineWidth = 0.25
            rectangle2Path.stroke()


            //// Shape 5 copy 2 Drawing
            var shape5Copy2Path = UIBezierPath()
            shape5Copy2Path.moveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.50001 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.67901 * deletChannelBtnClicked.height))
            shape5Copy2Path.addCurveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.32099 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.49999 * deletChannelBtnClicked.height), controlPoint1: CGPointMake(deletChannelBtnClicked.minX + 0.40131 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.67901 * deletChannelBtnClicked.height), controlPoint2: CGPointMake(deletChannelBtnClicked.minX + 0.32099 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.59872 * deletChannelBtnClicked.height))
            shape5Copy2Path.addCurveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.50001 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.32099 * deletChannelBtnClicked.height), controlPoint1: CGPointMake(deletChannelBtnClicked.minX + 0.32099 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.40129 * deletChannelBtnClicked.height), controlPoint2: CGPointMake(deletChannelBtnClicked.minX + 0.40131 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.32099 * deletChannelBtnClicked.height))
            shape5Copy2Path.addCurveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.67901 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.49999 * deletChannelBtnClicked.height), controlPoint1: CGPointMake(deletChannelBtnClicked.minX + 0.59872 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.32099 * deletChannelBtnClicked.height), controlPoint2: CGPointMake(deletChannelBtnClicked.minX + 0.67901 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.40129 * deletChannelBtnClicked.height))
            shape5Copy2Path.addCurveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.50001 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.67901 * deletChannelBtnClicked.height), controlPoint1: CGPointMake(deletChannelBtnClicked.minX + 0.67901 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.59872 * deletChannelBtnClicked.height), controlPoint2: CGPointMake(deletChannelBtnClicked.minX + 0.59872 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.67901 * deletChannelBtnClicked.height))
            shape5Copy2Path.closePath()
            shape5Copy2Path.moveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.50001 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.32653 * deletChannelBtnClicked.height))
            shape5Copy2Path.addCurveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.32654 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.49999 * deletChannelBtnClicked.height), controlPoint1: CGPointMake(deletChannelBtnClicked.minX + 0.40437 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.32653 * deletChannelBtnClicked.height), controlPoint2: CGPointMake(deletChannelBtnClicked.minX + 0.32654 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.40434 * deletChannelBtnClicked.height))
            shape5Copy2Path.addCurveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.50001 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.67347 * deletChannelBtnClicked.height), controlPoint1: CGPointMake(deletChannelBtnClicked.minX + 0.32654 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.59565 * deletChannelBtnClicked.height), controlPoint2: CGPointMake(deletChannelBtnClicked.minX + 0.40437 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.67347 * deletChannelBtnClicked.height))
            shape5Copy2Path.addCurveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.67347 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.49999 * deletChannelBtnClicked.height), controlPoint1: CGPointMake(deletChannelBtnClicked.minX + 0.59566 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.67347 * deletChannelBtnClicked.height), controlPoint2: CGPointMake(deletChannelBtnClicked.minX + 0.67347 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.59565 * deletChannelBtnClicked.height))
            shape5Copy2Path.addCurveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.50001 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.32653 * deletChannelBtnClicked.height), controlPoint1: CGPointMake(deletChannelBtnClicked.minX + 0.67347 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.40434 * deletChannelBtnClicked.height), controlPoint2: CGPointMake(deletChannelBtnClicked.minX + 0.59566 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.32653 * deletChannelBtnClicked.height))
            shape5Copy2Path.closePath()
            shape5Copy2Path.moveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.53904 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.57516 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.46097 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.57516 * deletChannelBtnClicked.height))
            shape5Copy2Path.addCurveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.45441 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.56847 * deletChannelBtnClicked.height), controlPoint1: CGPointMake(deletChannelBtnClicked.minX + 0.45759 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.57516 * deletChannelBtnClicked.height), controlPoint2: CGPointMake(deletChannelBtnClicked.minX + 0.45469 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.57222 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.44756 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.47875 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.55245 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.47875 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.54559 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.56847 * deletChannelBtnClicked.height))
            shape5Copy2Path.addCurveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.53904 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.57516 * deletChannelBtnClicked.height), controlPoint1: CGPointMake(deletChannelBtnClicked.minX + 0.54533 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.57222 * deletChannelBtnClicked.height), controlPoint2: CGPointMake(deletChannelBtnClicked.minX + 0.54246 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.57516 * deletChannelBtnClicked.height))
            shape5Copy2Path.closePath()
            shape5Copy2Path.moveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.45354 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.48430 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.45994 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.56805 * deletChannelBtnClicked.height))
            shape5Copy2Path.addCurveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.46097 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.56963 * deletChannelBtnClicked.height), controlPoint1: CGPointMake(deletChannelBtnClicked.minX + 0.46002 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.56901 * deletChannelBtnClicked.height), controlPoint2: CGPointMake(deletChannelBtnClicked.minX + 0.46066 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.56963 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.53904 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.56963 * deletChannelBtnClicked.height))
            shape5Copy2Path.addCurveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.54007 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.56806 * deletChannelBtnClicked.height), controlPoint1: CGPointMake(deletChannelBtnClicked.minX + 0.53936 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.56963 * deletChannelBtnClicked.height), controlPoint2: CGPointMake(deletChannelBtnClicked.minX + 0.54000 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.56901 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.54647 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.48430 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.45354 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.48430 * deletChannelBtnClicked.height))
            shape5Copy2Path.closePath()
            shape5Copy2Path.moveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.55497 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.47408 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.44504 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.47408 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.44504 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.45432 * deletChannelBtnClicked.height))
            shape5Copy2Path.addCurveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.45822 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.44043 * deletChannelBtnClicked.height), controlPoint1: CGPointMake(deletChannelBtnClicked.minX + 0.44504 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.44667 * deletChannelBtnClicked.height), controlPoint2: CGPointMake(deletChannelBtnClicked.minX + 0.45094 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.44043 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.54179 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.44043 * deletChannelBtnClicked.height))
            shape5Copy2Path.addCurveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.55497 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.45432 * deletChannelBtnClicked.height), controlPoint1: CGPointMake(deletChannelBtnClicked.minX + 0.54906 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.44043 * deletChannelBtnClicked.height), controlPoint2: CGPointMake(deletChannelBtnClicked.minX + 0.55497 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.44667 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.55497 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.47408 * deletChannelBtnClicked.height))
            shape5Copy2Path.closePath()
            shape5Copy2Path.moveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.45057 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.46854 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.54943 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.46854 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.54943 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.45432 * deletChannelBtnClicked.height))
            shape5Copy2Path.addCurveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.54179 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.44598 * deletChannelBtnClicked.height), controlPoint1: CGPointMake(deletChannelBtnClicked.minX + 0.54943 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.44972 * deletChannelBtnClicked.height), controlPoint2: CGPointMake(deletChannelBtnClicked.minX + 0.54600 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.44598 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.45822 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.44598 * deletChannelBtnClicked.height))
            shape5Copy2Path.addCurveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.45057 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.45432 * deletChannelBtnClicked.height), controlPoint1: CGPointMake(deletChannelBtnClicked.minX + 0.45401 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.44598 * deletChannelBtnClicked.height), controlPoint2: CGPointMake(deletChannelBtnClicked.minX + 0.45057 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.44972 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.45057 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.46854 * deletChannelBtnClicked.height))
            shape5Copy2Path.closePath()
            shape5Copy2Path.moveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.47687 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.43799 * deletChannelBtnClicked.height))
            shape5Copy2Path.addCurveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.47687 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.43143 * deletChannelBtnClicked.height), controlPoint1: CGPointMake(deletChannelBtnClicked.minX + 0.47687 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.43799 * deletChannelBtnClicked.height), controlPoint2: CGPointMake(deletChannelBtnClicked.minX + 0.47687 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.43505 * deletChannelBtnClicked.height))
            shape5Copy2Path.addCurveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.48381 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.42482 * deletChannelBtnClicked.height), controlPoint1: CGPointMake(deletChannelBtnClicked.minX + 0.47687 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.42778 * deletChannelBtnClicked.height), controlPoint2: CGPointMake(deletChannelBtnClicked.minX + 0.47998 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.42482 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.51620 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.42482 * deletChannelBtnClicked.height))
            shape5Copy2Path.addCurveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.52315 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.43143 * deletChannelBtnClicked.height), controlPoint1: CGPointMake(deletChannelBtnClicked.minX + 0.52004 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.42482 * deletChannelBtnClicked.height), controlPoint2: CGPointMake(deletChannelBtnClicked.minX + 0.52315 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.42778 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.52315 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.43799 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.47687 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.43799 * deletChannelBtnClicked.height))
            shape5Copy2Path.closePath()
            shape5Copy2Path.moveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.49417 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.54804 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.48584 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.54804 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.48584 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.48981 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.49417 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.48981 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.49417 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.54804 * deletChannelBtnClicked.height))
            shape5Copy2Path.closePath()
            shape5Copy2Path.moveToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.51416 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.54804 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.50584 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.54804 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.50584 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.48981 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.51416 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.48981 * deletChannelBtnClicked.height))
            shape5Copy2Path.addLineToPoint(CGPointMake(deletChannelBtnClicked.minX + 0.51416 * deletChannelBtnClicked.width, deletChannelBtnClicked.minY + 0.54804 * deletChannelBtnClicked.height))
            shape5Copy2Path.closePath()
            shape5Copy2Path.miterLimit = 100;

            shape5Copy2Path.lineCapStyle = kCGLineCapRound;

            shape5Copy2Path.lineJoinStyle = kCGLineJoinRound;

            iconClickedColor.setFill()
            shape5Copy2Path.fill()
            iconClickedColor.setStroke()
            shape5Copy2Path.lineWidth = 0.5
            shape5Copy2Path.stroke()


        }
    }

}


