//
//  WeshappMsgIconSK.swift
//  Weshapp
//
//  Created by SM on 14/02/2015.
//  Copyright (c) 2015 Weshapp. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class WeshappMsgIconSK : NSObject {

    //// Drawing Methods

    public class func drawMsgCanvas(#msgFrame: CGRect, sendMsgBtnClicked: Bool) {
        //// Color Declarations
        let red = UIColor(red: 1.000, green: 0.439, blue: 0.439, alpha: 1.000)
        let shape3StrokeColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let iconClickedColor = UIColor(red: 1.000, green: 0.788, blue: 0.788, alpha: 1.000)
        let btnClickedColor = UIColor(red: 0.890, green: 0.290, blue: 0.290, alpha: 1.000)
        let shape5Color = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let shape5StrokeColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)


        //// Subframes
        let sendMSGBTN: CGRect = CGRectMake(msgFrame.minX + floor(msgFrame.width * 0.00000 + 0.5), msgFrame.minY + floor(msgFrame.height * 0.00000 + 0.5), floor(msgFrame.width * 1.00000 + 0.5) - floor(msgFrame.width * 0.00000 + 0.5), floor(msgFrame.height * 1.00000 + 0.5) - floor(msgFrame.height * 0.00000 + 0.5))
        let sendMSGBTNClicked: CGRect = CGRectMake(msgFrame.minX + floor(msgFrame.width * 0.00000 + 0.5), msgFrame.minY + floor(msgFrame.height * 0.00000 + 0.5), floor(msgFrame.width * 1.00000 + 0.5) - floor(msgFrame.width * 0.00000 + 0.5), floor(msgFrame.height * 1.00000 + 0.5) - floor(msgFrame.height * 0.00000 + 0.5))


        //// sendMSGBTN
        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRectMake(sendMSGBTN.minX + floor(sendMSGBTN.width * 0.00000 + 0.5), sendMSGBTN.minY + floor(sendMSGBTN.height * 0.00000 + 0.5), floor(sendMSGBTN.width * 1.00000 + 0.5) - floor(sendMSGBTN.width * 0.00000 + 0.5), floor(sendMSGBTN.height * 1.00000 + 0.5) - floor(sendMSGBTN.height * 0.00000 + 0.5)))
        red.setFill()
        rectanglePath.fill()
        shape3StrokeColor.setStroke()
        rectanglePath.lineWidth = 0.25
        rectanglePath.stroke()


        //// Shape 5 Drawing
        var shape5Path = UIBezierPath()
        shape5Path.moveToPoint(CGPointMake(sendMSGBTN.minX + 0.50000 * sendMSGBTN.width, sendMSGBTN.minY + 0.67901 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.32099 * sendMSGBTN.width, sendMSGBTN.minY + 0.50000 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.40130 * sendMSGBTN.width, sendMSGBTN.minY + 0.67901 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.32099 * sendMSGBTN.width, sendMSGBTN.minY + 0.59872 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.50000 * sendMSGBTN.width, sendMSGBTN.minY + 0.32099 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.32099 * sendMSGBTN.width, sendMSGBTN.minY + 0.40128 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.40130 * sendMSGBTN.width, sendMSGBTN.minY + 0.32099 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.67901 * sendMSGBTN.width, sendMSGBTN.minY + 0.50000 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.59871 * sendMSGBTN.width, sendMSGBTN.minY + 0.32099 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.67901 * sendMSGBTN.width, sendMSGBTN.minY + 0.40128 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.50000 * sendMSGBTN.width, sendMSGBTN.minY + 0.67901 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.67901 * sendMSGBTN.width, sendMSGBTN.minY + 0.59872 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.59871 * sendMSGBTN.width, sendMSGBTN.minY + 0.67901 * sendMSGBTN.height))
        shape5Path.closePath()
        shape5Path.moveToPoint(CGPointMake(sendMSGBTN.minX + 0.50000 * sendMSGBTN.width, sendMSGBTN.minY + 0.32659 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.32658 * sendMSGBTN.width, sendMSGBTN.minY + 0.50000 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.40437 * sendMSGBTN.width, sendMSGBTN.minY + 0.32659 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.32658 * sendMSGBTN.width, sendMSGBTN.minY + 0.40439 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.50000 * sendMSGBTN.width, sendMSGBTN.minY + 0.67343 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.32658 * sendMSGBTN.width, sendMSGBTN.minY + 0.59563 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.40437 * sendMSGBTN.width, sendMSGBTN.minY + 0.67343 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.67343 * sendMSGBTN.width, sendMSGBTN.minY + 0.50000 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.59563 * sendMSGBTN.width, sendMSGBTN.minY + 0.67343 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.67343 * sendMSGBTN.width, sendMSGBTN.minY + 0.59563 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.50000 * sendMSGBTN.width, sendMSGBTN.minY + 0.32659 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.67343 * sendMSGBTN.width, sendMSGBTN.minY + 0.40439 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.59563 * sendMSGBTN.width, sendMSGBTN.minY + 0.32659 * sendMSGBTN.height))
        shape5Path.closePath()
        shape5Path.moveToPoint(CGPointMake(sendMSGBTN.minX + 0.58965 * sendMSGBTN.width, sendMSGBTN.minY + 0.58643 * sendMSGBTN.height))
        shape5Path.addLineToPoint(CGPointMake(sendMSGBTN.minX + 0.58149 * sendMSGBTN.width, sendMSGBTN.minY + 0.58081 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.52660 * sendMSGBTN.width, sendMSGBTN.minY + 0.54952 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.56396 * sendMSGBTN.width, sendMSGBTN.minY + 0.56872 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.53358 * sendMSGBTN.width, sendMSGBTN.minY + 0.54952 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.49489 * sendMSGBTN.width, sendMSGBTN.minY + 0.55460 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.51640 * sendMSGBTN.width, sendMSGBTN.minY + 0.55291 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.50579 * sendMSGBTN.width, sendMSGBTN.minY + 0.55460 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.41035 * sendMSGBTN.width, sendMSGBTN.minY + 0.48409 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.44827 * sendMSGBTN.width, sendMSGBTN.minY + 0.55460 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.41035 * sendMSGBTN.width, sendMSGBTN.minY + 0.52298 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.49489 * sendMSGBTN.width, sendMSGBTN.minY + 0.41357 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.41035 * sendMSGBTN.width, sendMSGBTN.minY + 0.44522 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.44827 * sendMSGBTN.width, sendMSGBTN.minY + 0.41357 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.57941 * sendMSGBTN.width, sendMSGBTN.minY + 0.48409 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.54149 * sendMSGBTN.width, sendMSGBTN.minY + 0.41357 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.57941 * sendMSGBTN.width, sendMSGBTN.minY + 0.44522 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.56662 * sendMSGBTN.width, sendMSGBTN.minY + 0.52145 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.57941 * sendMSGBTN.width, sendMSGBTN.minY + 0.49736 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.57498 * sendMSGBTN.width, sendMSGBTN.minY + 0.51027 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.58563 * sendMSGBTN.width, sendMSGBTN.minY + 0.57736 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.56487 * sendMSGBTN.width, sendMSGBTN.minY + 0.52558 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.57511 * sendMSGBTN.width, sendMSGBTN.minY + 0.55371 * sendMSGBTN.height))
        shape5Path.addLineToPoint(CGPointMake(sendMSGBTN.minX + 0.58965 * sendMSGBTN.width, sendMSGBTN.minY + 0.58643 * sendMSGBTN.height))
        shape5Path.closePath()
        shape5Path.moveToPoint(CGPointMake(sendMSGBTN.minX + 0.52660 * sendMSGBTN.width, sendMSGBTN.minY + 0.54396 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.57668 * sendMSGBTN.width, sendMSGBTN.minY + 0.57083 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.53516 * sendMSGBTN.width, sendMSGBTN.minY + 0.54396 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.56265 * sendMSGBTN.width, sendMSGBTN.minY + 0.56147 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.56216 * sendMSGBTN.width, sendMSGBTN.minY + 0.51811 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.56806 * sendMSGBTN.width, sendMSGBTN.minY + 0.55063 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.55790 * sendMSGBTN.width, sendMSGBTN.minY + 0.52376 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.57384 * sendMSGBTN.width, sendMSGBTN.minY + 0.48409 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.56979 * sendMSGBTN.width, sendMSGBTN.minY + 0.50789 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.57384 * sendMSGBTN.width, sendMSGBTN.minY + 0.49613 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.49489 * sendMSGBTN.width, sendMSGBTN.minY + 0.41915 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.57384 * sendMSGBTN.width, sendMSGBTN.minY + 0.44829 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.53842 * sendMSGBTN.width, sendMSGBTN.minY + 0.41915 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.41593 * sendMSGBTN.width, sendMSGBTN.minY + 0.48409 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.45135 * sendMSGBTN.width, sendMSGBTN.minY + 0.41915 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.41593 * sendMSGBTN.width, sendMSGBTN.minY + 0.44829 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.49489 * sendMSGBTN.width, sendMSGBTN.minY + 0.54903 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.41593 * sendMSGBTN.width, sendMSGBTN.minY + 0.51991 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.45135 * sendMSGBTN.width, sendMSGBTN.minY + 0.54903 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.52467 * sendMSGBTN.width, sendMSGBTN.minY + 0.54425 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.50518 * sendMSGBTN.width, sendMSGBTN.minY + 0.54903 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.51520 * sendMSGBTN.width, sendMSGBTN.minY + 0.54743 * sendMSGBTN.height))
        shape5Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.52660 * sendMSGBTN.width, sendMSGBTN.minY + 0.54396 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.52525 * sendMSGBTN.width, sendMSGBTN.minY + 0.54407 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.52588 * sendMSGBTN.width, sendMSGBTN.minY + 0.54396 * sendMSGBTN.height))
        shape5Path.closePath()
        shape5Path.miterLimit = 100;

        shape5Path.lineCapStyle = kCGLineCapRound;

        shape5Path.lineJoinStyle = kCGLineJoinRound;

        shape5Color.setFill()
        shape5Path.fill()
        shape5StrokeColor.setStroke()
        shape5Path.lineWidth = 0.5
        shape5Path.stroke()




        if (sendMsgBtnClicked) {
            //// sendMSGBTNClicked
            //// Rectangle 2 Drawing
            let rectangle2Path = UIBezierPath(rect: CGRectMake(sendMSGBTNClicked.minX + floor(sendMSGBTNClicked.width * 0.00000 + 0.5), sendMSGBTNClicked.minY + floor(sendMSGBTNClicked.height * 0.00000 + 0.5), floor(sendMSGBTNClicked.width * 1.00000 + 0.5) - floor(sendMSGBTNClicked.width * 0.00000 + 0.5), floor(sendMSGBTNClicked.height * 1.00000 + 0.5) - floor(sendMSGBTNClicked.height * 0.00000 + 0.5)))
            btnClickedColor.setFill()
            rectangle2Path.fill()
            shape3StrokeColor.setStroke()
            rectangle2Path.lineWidth = 0.25
            rectangle2Path.stroke()


            //// Shape Drawing
            var shapePath = UIBezierPath()
            shapePath.moveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.50000 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.67901 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.32099 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.50000 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.40130 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.67901 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.32099 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.59872 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.50000 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.32099 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.32099 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.40128 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.40130 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.32099 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.67901 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.50000 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.59871 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.32099 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.67901 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.40128 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.50000 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.67901 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.67901 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.59872 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.59871 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.67901 * sendMSGBTNClicked.height))
            shapePath.closePath()
            shapePath.moveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.50000 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.32659 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.32658 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.50000 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.40437 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.32659 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.32658 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.40439 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.50000 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.67343 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.32658 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.59563 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.40437 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.67343 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.67343 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.50000 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.59563 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.67343 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.67343 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.59563 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.50000 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.32659 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.67343 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.40439 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.59563 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.32659 * sendMSGBTNClicked.height))
            shapePath.closePath()
            shapePath.moveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.58965 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.58643 * sendMSGBTNClicked.height))
            shapePath.addLineToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.58149 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.58081 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.52660 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.54952 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.56396 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.56872 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.53358 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.54952 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.49489 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.55460 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.51640 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.55291 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.50579 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.55460 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.41035 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.48409 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.44827 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.55460 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.41035 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.52298 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.49489 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.41357 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.41035 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.44522 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.44827 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.41357 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.57941 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.48409 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.54149 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.41357 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.57941 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.44522 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.56662 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.52145 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.57941 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.49736 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.57498 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.51027 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.58563 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.57736 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.56487 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.52558 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.57511 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.55371 * sendMSGBTNClicked.height))
            shapePath.addLineToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.58965 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.58643 * sendMSGBTNClicked.height))
            shapePath.closePath()
            shapePath.moveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.52660 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.54396 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.57668 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.57083 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.53516 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.54396 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.56265 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.56147 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.56216 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.51811 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.56806 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.55063 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.55790 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.52376 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.57384 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.48409 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.56979 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.50789 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.57384 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.49613 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.49489 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.41915 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.57384 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.44829 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.53842 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.41915 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.41593 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.48409 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.45135 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.41915 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.41593 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.44829 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.49489 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.54903 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.41593 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.51991 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.45135 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.54903 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.52467 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.54425 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.50518 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.54903 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.51520 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.54743 * sendMSGBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.52660 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.54396 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.52525 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.54407 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.52588 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.54396 * sendMSGBTNClicked.height))
            shapePath.closePath()
            shapePath.miterLimit = 100;

            shapePath.lineCapStyle = kCGLineCapRound;

            shapePath.lineJoinStyle = kCGLineJoinRound;

            iconClickedColor.setFill()
            shapePath.fill()
            iconClickedColor.setStroke()
            shapePath.lineWidth = 0.5
            shapePath.stroke()


        }
    }

}