//
//  WeshappChevronSK.swift
//  Weshapp
//
//  Created by SM on 08/02/2015.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class WeshappChevronSK : NSObject {

    //// Drawing Methods

    public class func drawChevronCanvas(#chevronFrame: CGRect) {
        //// Color Declarations
        let arrowColor = UIColor(red: 0.956, green: 0.470, blue: 0.488, alpha: 1.000)


        //// Subframes
        let group: CGRect = CGRectMake(chevronFrame.minX + floor(chevronFrame.width * -0.00028 - 0.5) + 1, chevronFrame.minY, floor(chevronFrame.width * 0.99986 - 0.5) - floor(chevronFrame.width * -0.00028 - 0.5) + 0, chevronFrame.height + 0.01)


        //// Group
        //// chevron Drawing
        var chevronPath = UIBezierPath()
        chevronPath.moveToPoint(CGPointMake(group.minX + 0.95635 * group.width, group.minY + 0.56639 * group.height))
        chevronPath.addCurveToPoint(CGPointMake(group.minX + 0.92259 * group.width, group.minY + 0.57966 * group.height), controlPoint1: CGPointMake(group.minX + 0.94638 * group.width, group.minY + 0.57229 * group.height), controlPoint2: CGPointMake(group.minX + 0.93430 * group.width, group.minY + 0.57576 * group.height))
        chevronPath.addLineToPoint(CGPointMake(group.minX + 0.25695 * group.width, group.minY + 0.97389 * group.height))
        chevronPath.addCurveToPoint(CGPointMake(group.minX + 0.04408 * group.width, group.minY + 0.97389 * group.height), controlPoint1: CGPointMake(group.minX + 0.19816 * group.width, group.minY + 1.00870 * group.height), controlPoint2: CGPointMake(group.minX + 0.10286 * group.width, group.minY + 1.00870 * group.height))
        chevronPath.addCurveToPoint(CGPointMake(group.minX + 0.04408 * group.width, group.minY + 0.84783 * group.height), controlPoint1: CGPointMake(group.minX + -0.01469 * group.width, group.minY + 0.93908 * group.height), controlPoint2: CGPointMake(group.minX + -0.01469 * group.width, group.minY + 0.88264 * group.height))
        chevronPath.addLineToPoint(CGPointMake(group.minX + 0.63139 * group.width, group.minY + 0.50000 * group.height))
        chevronPath.addLineToPoint(CGPointMake(group.minX + 0.04408 * group.width, group.minY + 0.15217 * group.height))
        chevronPath.addCurveToPoint(CGPointMake(group.minX + 0.04408 * group.width, group.minY + 0.02611 * group.height), controlPoint1: CGPointMake(group.minX + -0.01469 * group.width, group.minY + 0.11736 * group.height), controlPoint2: CGPointMake(group.minX + -0.01469 * group.width, group.minY + 0.06092 * group.height))
        chevronPath.addCurveToPoint(CGPointMake(group.minX + 0.25695 * group.width, group.minY + 0.02611 * group.height), controlPoint1: CGPointMake(group.minX + 0.10286 * group.width, group.minY + -0.00870 * group.height), controlPoint2: CGPointMake(group.minX + 0.19816 * group.width, group.minY + -0.00870 * group.height))
        chevronPath.addLineToPoint(CGPointMake(group.minX + 0.92259 * group.width, group.minY + 0.42034 * group.height))
        chevronPath.addCurveToPoint(CGPointMake(group.minX + 0.95635 * group.width, group.minY + 0.43361 * group.height), controlPoint1: CGPointMake(group.minX + 0.93430 * group.width, group.minY + 0.42424 * group.height), controlPoint2: CGPointMake(group.minX + 0.94638 * group.width, group.minY + 0.42771 * group.height))
        chevronPath.addCurveToPoint(CGPointMake(group.minX + 0.99989 * group.width, group.minY + 0.50000 * group.height), controlPoint1: CGPointMake(group.minX + 0.98719 * group.width, group.minY + 0.45188 * group.height), controlPoint2: CGPointMake(group.minX + 1.00141 * group.width, group.minY + 0.47608 * group.height))
        chevronPath.addCurveToPoint(CGPointMake(group.minX + 0.95635 * group.width, group.minY + 0.56639 * group.height), controlPoint1: CGPointMake(group.minX + 1.00141 * group.width, group.minY + 0.52392 * group.height), controlPoint2: CGPointMake(group.minX + 0.98719 * group.width, group.minY + 0.54812 * group.height))
        chevronPath.closePath()
        arrowColor.setFill()
        chevronPath.fill()
    }

}
