//
//  WeshappRedButtonSK.swift
//  Weshapp
//
//  Created by SM on 18/02/2015.
//  Copyright (c) 2015 Weshapp. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class WeshappRedButtonSK : NSObject {

    //// Drawing Methods

    public class func drawRedArrowCanvas(#buttonFrame: CGRect, btnClicked: Bool, notClicked: Bool) {
        //// Color Declarations
        let btnColor = UIColor(red: 1.000, green: 0.349, blue: 0.349, alpha: 1.000)
        let arrowPickColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let arrowLineColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let btnClickedColor = UIColor(red: 0.888, green: 0.290, blue: 0.290, alpha: 1.000)


        //// Subframes
        let arrowFrame = CGRectMake(buttonFrame.minX + floor((buttonFrame.width - 20) * 0.50144 + 0.5), buttonFrame.minY + floor((buttonFrame.height - 21) * 0.53061 + 0.5), 20, 21)
        let arrowGroup: CGRect = CGRectMake(arrowFrame.minX + floor((arrowFrame.width - 19.92) * -4.79689 - 0.1) + 0.6, arrowFrame.minY + floor((arrowFrame.height - 22) * 0.61817 - 0.12) + 0.62, 19.92, 22)


        if (notClicked) {
            //// freeButton Drawing
            var freeButtonPath = UIBezierPath()
            freeButtonPath.moveToPoint(CGPointMake(buttonFrame.minX + 0.00000 * buttonFrame.width, buttonFrame.minY + -0.00000 * buttonFrame.height))
            freeButtonPath.addLineToPoint(CGPointMake(buttonFrame.minX + 1.00000 * buttonFrame.width, buttonFrame.minY + -0.00000 * buttonFrame.height))
            freeButtonPath.addLineToPoint(CGPointMake(buttonFrame.minX + 1.00000 * buttonFrame.width, buttonFrame.minY + 1.00000 * buttonFrame.height))
            freeButtonPath.addLineToPoint(CGPointMake(buttonFrame.minX + 0.00000 * buttonFrame.width, buttonFrame.minY + 1.00000 * buttonFrame.height))
            freeButtonPath.addLineToPoint(CGPointMake(buttonFrame.minX + 0.00000 * buttonFrame.width, buttonFrame.minY + -0.00000 * buttonFrame.height))
            freeButtonPath.closePath()
            btnColor.setFill()
            freeButtonPath.fill()
        }


        if (btnClicked) {
            //// pressedButton Drawing
            var pressedButtonPath = UIBezierPath()
            pressedButtonPath.moveToPoint(CGPointMake(buttonFrame.minX + 0.00000 * buttonFrame.width, buttonFrame.minY + 0.00000 * buttonFrame.height))
            pressedButtonPath.addLineToPoint(CGPointMake(buttonFrame.minX + 1.00000 * buttonFrame.width, buttonFrame.minY + 0.00000 * buttonFrame.height))
            pressedButtonPath.addLineToPoint(CGPointMake(buttonFrame.minX + 1.00000 * buttonFrame.width, buttonFrame.minY + 1.00000 * buttonFrame.height))
            pressedButtonPath.addLineToPoint(CGPointMake(buttonFrame.minX + 0.00000 * buttonFrame.width, buttonFrame.minY + 1.00000 * buttonFrame.height))
            pressedButtonPath.addLineToPoint(CGPointMake(buttonFrame.minX + 0.00000 * buttonFrame.width, buttonFrame.minY + 0.00000 * buttonFrame.height))
            pressedButtonPath.closePath()
            btnClickedColor.setFill()
            pressedButtonPath.fill()
        }


        //// ArrowGroup
        //// Arrow Pick Drawing
        var arrowPickPath = UIBezierPath()
        arrowPickPath.moveToPoint(CGPointMake(arrowGroup.minX + 9.92, arrowGroup.minY))
        arrowPickPath.addLineToPoint(CGPointMake(arrowGroup.minX + 19.92, arrowGroup.minY + 10.77))
        arrowPickPath.addLineToPoint(CGPointMake(arrowGroup.minX + 18.92, arrowGroup.minY + 11.84))
        arrowPickPath.addLineToPoint(CGPointMake(arrowGroup.minX + 8.92, arrowGroup.minY + 1.08))
        arrowPickPath.addLineToPoint(CGPointMake(arrowGroup.minX + 9.92, arrowGroup.minY))
        arrowPickPath.closePath()
        arrowPickPath.moveToPoint(CGPointMake(arrowGroup.minX + 8.92, arrowGroup.minY + 20.92))
        arrowPickPath.addLineToPoint(CGPointMake(arrowGroup.minX + 18.92, arrowGroup.minY + 10.15))
        arrowPickPath.addLineToPoint(CGPointMake(arrowGroup.minX + 19.92, arrowGroup.minY + 11.23))
        arrowPickPath.addLineToPoint(CGPointMake(arrowGroup.minX + 9.92, arrowGroup.minY + 22))
        arrowPickPath.addLineToPoint(CGPointMake(arrowGroup.minX + 8.92, arrowGroup.minY + 20.92))
        arrowPickPath.closePath()
        arrowPickColor.setFill()
        arrowPickPath.fill()


        //// Arrow Line Drawing
        var arrowLinePath = UIBezierPath()
        arrowLinePath.moveToPoint(CGPointMake(arrowGroup.minX + 18, arrowGroup.minY + 10.24))
        arrowLinePath.addLineToPoint(CGPointMake(arrowGroup.minX, arrowGroup.minY + 10.24))
        arrowLinePath.addLineToPoint(CGPointMake(arrowGroup.minX, arrowGroup.minY + 11.74))
        arrowLinePath.addLineToPoint(CGPointMake(arrowGroup.minX + 18, arrowGroup.minY + 11.74))
        arrowLinePath.addLineToPoint(CGPointMake(arrowGroup.minX + 18, arrowGroup.minY + 10.24))
        arrowLinePath.closePath()
        arrowLineColor.setFill()
        arrowLinePath.fill()
    }

}
