//
//  WeshappFriendRequestSK.swift
//  Weshapp
//
//  Created by SM on 14/02/2015.
//  Copyright (c) 2015 Weshapp. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class WeshappFriendRequestSK : NSObject {

    //// Drawing Methods

    public class func drawFriendCanvas(#friendFrame: CGRect, sendMsgBtnClicked: Bool) {
        //// Color Declarations
        let red = UIColor(red: 1.000, green: 0.439, blue: 0.439, alpha: 1.000)
        let shape3StrokeColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let iconClickedColor = UIColor(red: 1.000, green: 0.788, blue: 0.788, alpha: 1.000)
        let btnClickedColor = UIColor(red: 0.890, green: 0.290, blue: 0.290, alpha: 1.000)
        let shape6Color = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let shape6StrokeColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)


        //// Subframes
        let sendMSGBTN: CGRect = CGRectMake(friendFrame.minX + floor(friendFrame.width * 0.00000 + 0.5), friendFrame.minY + floor(friendFrame.height * 0.00000 + 0.5), floor(friendFrame.width * 1.00000 + 0.5) - floor(friendFrame.width * 0.00000 + 0.5), floor(friendFrame.height * 1.00000 + 0.5) - floor(friendFrame.height * 0.00000 + 0.5))
        let sendMSGBTNClicked: CGRect = CGRectMake(friendFrame.minX + floor(friendFrame.width * 0.00000 + 0.5), friendFrame.minY + floor(friendFrame.height * 0.00000 + 0.5), floor(friendFrame.width * 1.00000 + 0.5) - floor(friendFrame.width * 0.00000 + 0.5), floor(friendFrame.height * 1.00000 + 0.5) - floor(friendFrame.height * 0.00000 + 0.5))


        //// sendMSGBTN
        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRectMake(sendMSGBTN.minX + floor(sendMSGBTN.width * 0.00000 + 0.5), sendMSGBTN.minY + floor(sendMSGBTN.height * 0.00000 + 0.5), floor(sendMSGBTN.width * 1.00000 + 0.5) - floor(sendMSGBTN.width * 0.00000 + 0.5), floor(sendMSGBTN.height * 1.00000 + 0.5) - floor(sendMSGBTN.height * 0.00000 + 0.5)))
        red.setFill()
        rectanglePath.fill()
        shape3StrokeColor.setStroke()
        rectanglePath.lineWidth = 0.25
        rectanglePath.stroke()


        //// Shape 6 Drawing
        var shape6Path = UIBezierPath()
        shape6Path.moveToPoint(CGPointMake(sendMSGBTN.minX + 0.49999 * sendMSGBTN.width, sendMSGBTN.minY + 0.67901 * sendMSGBTN.height))
        shape6Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.32099 * sendMSGBTN.width, sendMSGBTN.minY + 0.50000 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.40129 * sendMSGBTN.width, sendMSGBTN.minY + 0.67901 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.32099 * sendMSGBTN.width, sendMSGBTN.minY + 0.59871 * sendMSGBTN.height))
        shape6Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.49999 * sendMSGBTN.width, sendMSGBTN.minY + 0.32099 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.32099 * sendMSGBTN.width, sendMSGBTN.minY + 0.40129 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.40129 * sendMSGBTN.width, sendMSGBTN.minY + 0.32099 * sendMSGBTN.height))
        shape6Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.67901 * sendMSGBTN.width, sendMSGBTN.minY + 0.50000 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.59871 * sendMSGBTN.width, sendMSGBTN.minY + 0.32099 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.67901 * sendMSGBTN.width, sendMSGBTN.minY + 0.40129 * sendMSGBTN.height))
        shape6Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.49999 * sendMSGBTN.width, sendMSGBTN.minY + 0.67901 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.67901 * sendMSGBTN.width, sendMSGBTN.minY + 0.59871 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.59871 * sendMSGBTN.width, sendMSGBTN.minY + 0.67901 * sendMSGBTN.height))
        shape6Path.closePath()
        shape6Path.moveToPoint(CGPointMake(sendMSGBTN.minX + 0.49999 * sendMSGBTN.width, sendMSGBTN.minY + 0.32653 * sendMSGBTN.height))
        shape6Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.32653 * sendMSGBTN.width, sendMSGBTN.minY + 0.50000 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.40435 * sendMSGBTN.width, sendMSGBTN.minY + 0.32653 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.32653 * sendMSGBTN.width, sendMSGBTN.minY + 0.40435 * sendMSGBTN.height))
        shape6Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.49999 * sendMSGBTN.width, sendMSGBTN.minY + 0.67347 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.32653 * sendMSGBTN.width, sendMSGBTN.minY + 0.59566 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.40435 * sendMSGBTN.width, sendMSGBTN.minY + 0.67347 * sendMSGBTN.height))
        shape6Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.67348 * sendMSGBTN.width, sendMSGBTN.minY + 0.50000 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.59566 * sendMSGBTN.width, sendMSGBTN.minY + 0.67347 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.67348 * sendMSGBTN.width, sendMSGBTN.minY + 0.59566 * sendMSGBTN.height))
        shape6Path.addCurveToPoint(CGPointMake(sendMSGBTN.minX + 0.49999 * sendMSGBTN.width, sendMSGBTN.minY + 0.32653 * sendMSGBTN.height), controlPoint1: CGPointMake(sendMSGBTN.minX + 0.67348 * sendMSGBTN.width, sendMSGBTN.minY + 0.40435 * sendMSGBTN.height), controlPoint2: CGPointMake(sendMSGBTN.minX + 0.59566 * sendMSGBTN.width, sendMSGBTN.minY + 0.32653 * sendMSGBTN.height))
        shape6Path.closePath()
        shape6Path.moveToPoint(CGPointMake(sendMSGBTN.minX + 0.50695 * sendMSGBTN.width, sendMSGBTN.minY + 0.55861 * sendMSGBTN.height))
        shape6Path.addLineToPoint(CGPointMake(sendMSGBTN.minX + 0.49268 * sendMSGBTN.width, sendMSGBTN.minY + 0.55861 * sendMSGBTN.height))
        shape6Path.addLineToPoint(CGPointMake(sendMSGBTN.minX + 0.49268 * sendMSGBTN.width, sendMSGBTN.minY + 0.50695 * sendMSGBTN.height))
        shape6Path.addLineToPoint(CGPointMake(sendMSGBTN.minX + 0.44138 * sendMSGBTN.width, sendMSGBTN.minY + 0.50695 * sendMSGBTN.height))
        shape6Path.addLineToPoint(CGPointMake(sendMSGBTN.minX + 0.44138 * sendMSGBTN.width, sendMSGBTN.minY + 0.49269 * sendMSGBTN.height))
        shape6Path.addLineToPoint(CGPointMake(sendMSGBTN.minX + 0.49268 * sendMSGBTN.width, sendMSGBTN.minY + 0.49269 * sendMSGBTN.height))
        shape6Path.addLineToPoint(CGPointMake(sendMSGBTN.minX + 0.49268 * sendMSGBTN.width, sendMSGBTN.minY + 0.44138 * sendMSGBTN.height))
        shape6Path.addLineToPoint(CGPointMake(sendMSGBTN.minX + 0.50695 * sendMSGBTN.width, sendMSGBTN.minY + 0.44138 * sendMSGBTN.height))
        shape6Path.addLineToPoint(CGPointMake(sendMSGBTN.minX + 0.50695 * sendMSGBTN.width, sendMSGBTN.minY + 0.49269 * sendMSGBTN.height))
        shape6Path.addLineToPoint(CGPointMake(sendMSGBTN.minX + 0.55862 * sendMSGBTN.width, sendMSGBTN.minY + 0.49269 * sendMSGBTN.height))
        shape6Path.addLineToPoint(CGPointMake(sendMSGBTN.minX + 0.55862 * sendMSGBTN.width, sendMSGBTN.minY + 0.50695 * sendMSGBTN.height))
        shape6Path.addLineToPoint(CGPointMake(sendMSGBTN.minX + 0.50695 * sendMSGBTN.width, sendMSGBTN.minY + 0.50695 * sendMSGBTN.height))
        shape6Path.addLineToPoint(CGPointMake(sendMSGBTN.minX + 0.50695 * sendMSGBTN.width, sendMSGBTN.minY + 0.55861 * sendMSGBTN.height))
        shape6Path.closePath()
        shape6Path.miterLimit = 100;

        shape6Path.lineCapStyle = kCGLineCapRound;

        shape6Path.lineJoinStyle = kCGLineJoinRound;

        shape6Color.setFill()
        shape6Path.fill()
        shape6StrokeColor.setStroke()
        shape6Path.lineWidth = 0.5
        shape6Path.stroke()




        if (sendMsgBtnClicked) {
            //// sendMSGBTNClicked
            //// Rectangle 2 Drawing
            let rectangle2Path = UIBezierPath(rect: CGRectMake(sendMSGBTNClicked.minX + floor(sendMSGBTNClicked.width * 0.00000 + 0.5), sendMSGBTNClicked.minY + floor(sendMSGBTNClicked.height * 0.00000 + 0.5), floor(sendMSGBTNClicked.width * 1.00000 + 0.5) - floor(sendMSGBTNClicked.width * 0.00000 + 0.5), floor(sendMSGBTNClicked.height * 1.00000 + 0.5) - floor(sendMSGBTNClicked.height * 0.00000 + 0.5)))
            btnClickedColor.setFill()
            rectangle2Path.fill()
            shape3StrokeColor.setStroke()
            rectangle2Path.lineWidth = 0.25
            rectangle2Path.stroke()


            //// CircleShape Drawing
            var circleShapePath = UIBezierPath()
            circleShapePath.moveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.49999 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.67901 * sendMSGBTNClicked.height))
            circleShapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.32099 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.50000 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.40129 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.67901 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.32099 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.59871 * sendMSGBTNClicked.height))
            circleShapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.49999 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.32099 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.32099 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.40129 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.40129 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.32099 * sendMSGBTNClicked.height))
            circleShapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.67901 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.50000 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.59871 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.32099 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.67901 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.40129 * sendMSGBTNClicked.height))
            circleShapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.49999 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.67901 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.67901 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.59871 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.59871 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.67901 * sendMSGBTNClicked.height))
            circleShapePath.closePath()
            circleShapePath.moveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.49999 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.32653 * sendMSGBTNClicked.height))
            circleShapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.32653 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.50000 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.40435 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.32653 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.32653 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.40435 * sendMSGBTNClicked.height))
            circleShapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.49999 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.67347 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.32653 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.59566 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.40435 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.67347 * sendMSGBTNClicked.height))
            circleShapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.67348 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.50000 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.59566 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.67347 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.67348 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.59566 * sendMSGBTNClicked.height))
            circleShapePath.addCurveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.49999 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.32653 * sendMSGBTNClicked.height), controlPoint1: CGPointMake(sendMSGBTNClicked.minX + 0.67348 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.40435 * sendMSGBTNClicked.height), controlPoint2: CGPointMake(sendMSGBTNClicked.minX + 0.59566 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.32653 * sendMSGBTNClicked.height))
            circleShapePath.closePath()
            circleShapePath.moveToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.50695 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.55861 * sendMSGBTNClicked.height))
            circleShapePath.addLineToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.49268 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.55861 * sendMSGBTNClicked.height))
            circleShapePath.addLineToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.49268 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.50695 * sendMSGBTNClicked.height))
            circleShapePath.addLineToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.44138 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.50695 * sendMSGBTNClicked.height))
            circleShapePath.addLineToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.44138 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.49269 * sendMSGBTNClicked.height))
            circleShapePath.addLineToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.49268 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.49269 * sendMSGBTNClicked.height))
            circleShapePath.addLineToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.49268 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.44138 * sendMSGBTNClicked.height))
            circleShapePath.addLineToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.50695 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.44138 * sendMSGBTNClicked.height))
            circleShapePath.addLineToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.50695 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.49269 * sendMSGBTNClicked.height))
            circleShapePath.addLineToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.55862 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.49269 * sendMSGBTNClicked.height))
            circleShapePath.addLineToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.55862 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.50695 * sendMSGBTNClicked.height))
            circleShapePath.addLineToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.50695 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.50695 * sendMSGBTNClicked.height))
            circleShapePath.addLineToPoint(CGPointMake(sendMSGBTNClicked.minX + 0.50695 * sendMSGBTNClicked.width, sendMSGBTNClicked.minY + 0.55861 * sendMSGBTNClicked.height))
            circleShapePath.closePath()
            circleShapePath.miterLimit = 100;

            circleShapePath.lineCapStyle = kCGLineCapRound;

            circleShapePath.lineJoinStyle = kCGLineJoinRound;

            iconClickedColor.setFill()
            circleShapePath.fill()
            iconClickedColor.setStroke()
            circleShapePath.lineWidth = 0.5
            circleShapePath.stroke()


        }
    }

}

