//
//  WeshappPlayPauseSK.swift
//  Weshapp
//
//  Created by SM on 14/02/2015.
//  Copyright (c) 2015 Weshapp. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class WeshappPlayPauseSK : NSObject {

    //// Drawing Methods

    public class func drawPauseCanvas(#frame: CGRect, playBtnClicked: Bool, pauseBtnClicked: Bool, channelState: Bool) {
        //// Color Declarations
        let red = UIColor(red: 1.000, green: 0.439, blue: 0.439, alpha: 1.000)
        let shape3StrokeColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let iconClickedColor = UIColor(red: 1.000, green: 0.788, blue: 0.788, alpha: 1.000)
        var iconClickedColorHueComponent: CGFloat = 1,
            iconClickedColorSaturationComponent: CGFloat = 1,
            iconClickedColorBrightnessComponent: CGFloat = 1
        iconClickedColor.getHue(&iconClickedColorHueComponent, saturation: &iconClickedColorSaturationComponent, brightness: &iconClickedColorBrightnessComponent, alpha: nil)

        let shape4StrokeColor = UIColor(hue: iconClickedColorHueComponent, saturation: 0, brightness: iconClickedColorBrightnessComponent, alpha: CGColorGetAlpha(iconClickedColor.CGColor))
        let btnClickedColor = UIColor(red: 0.890, green: 0.290, blue: 0.290, alpha: 1.000)
        let shape4Color = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)


        //// Subframes
        let pauseBTN: CGRect = CGRectMake(frame.minX + floor(frame.width * 0.00000 + 0.5), frame.minY + floor(frame.height * 0.00000 + 0.5), floor(frame.width * 1.00000 + 0.5) - floor(frame.width * 0.00000 + 0.5), floor(frame.height * 1.00000 + 0.5) - floor(frame.height * 0.00000 + 0.5))
        let pauseBTNClicked: CGRect = CGRectMake(frame.minX + floor(frame.width * 0.00000 + 0.5), frame.minY + floor(frame.height * 0.00000 + 0.5), floor(frame.width * 1.00000 + 0.5) - floor(frame.width * 0.00000 + 0.5), floor(frame.height * 1.00000 + 0.5) - floor(frame.height * 0.00000 + 0.5))
        let playBTN: CGRect = CGRectMake(frame.minX + floor(frame.width * 0.00000 + 0.5), frame.minY + floor(frame.height * 0.00000 + 0.5), floor(frame.width * 1.00000 + 0.5) - floor(frame.width * 0.00000 + 0.5), floor(frame.height * 1.00000 + 0.5) - floor(frame.height * 0.00000 + 0.5))
        let playBTNClicked: CGRect = CGRectMake(frame.minX + floor(frame.width * 0.00000 + 0.5), frame.minY + floor(frame.height * 0.00000 + 0.5), floor(frame.width * 1.00000 + 0.5) - floor(frame.width * 0.00000 + 0.5), floor(frame.height * 1.00000 + 0.5) - floor(frame.height * 0.00000 + 0.5))


        //// PauseBTN
        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRectMake(pauseBTN.minX + floor(pauseBTN.width * 0.00000 + 0.5), pauseBTN.minY + floor(pauseBTN.height * 0.00000 + 0.5), floor(pauseBTN.width * 1.00000 + 0.5) - floor(pauseBTN.width * 0.00000 + 0.5), floor(pauseBTN.height * 1.00000 + 0.5) - floor(pauseBTN.height * 0.00000 + 0.5)))
        red.setFill()
        rectanglePath.fill()
        shape3StrokeColor.setStroke()
        rectanglePath.lineWidth = 0.25
        rectanglePath.stroke()


        //// shape3 Drawing
        var shape3Path = UIBezierPath()
        shape3Path.moveToPoint(CGPointMake(pauseBTN.minX + 0.50000 * pauseBTN.width, pauseBTN.minY + 0.67901 * pauseBTN.height))
        shape3Path.addCurveToPoint(CGPointMake(pauseBTN.minX + 0.32099 * pauseBTN.width, pauseBTN.minY + 0.49999 * pauseBTN.height), controlPoint1: CGPointMake(pauseBTN.minX + 0.40127 * pauseBTN.width, pauseBTN.minY + 0.67901 * pauseBTN.height), controlPoint2: CGPointMake(pauseBTN.minX + 0.32099 * pauseBTN.width, pauseBTN.minY + 0.59870 * pauseBTN.height))
        shape3Path.addCurveToPoint(CGPointMake(pauseBTN.minX + 0.50000 * pauseBTN.width, pauseBTN.minY + 0.32099 * pauseBTN.height), controlPoint1: CGPointMake(pauseBTN.minX + 0.32099 * pauseBTN.width, pauseBTN.minY + 0.40130 * pauseBTN.height), controlPoint2: CGPointMake(pauseBTN.minX + 0.40127 * pauseBTN.width, pauseBTN.minY + 0.32099 * pauseBTN.height))
        shape3Path.addCurveToPoint(CGPointMake(pauseBTN.minX + 0.67901 * pauseBTN.width, pauseBTN.minY + 0.49999 * pauseBTN.height), controlPoint1: CGPointMake(pauseBTN.minX + 0.59871 * pauseBTN.width, pauseBTN.minY + 0.32099 * pauseBTN.height), controlPoint2: CGPointMake(pauseBTN.minX + 0.67901 * pauseBTN.width, pauseBTN.minY + 0.40130 * pauseBTN.height))
        shape3Path.addCurveToPoint(CGPointMake(pauseBTN.minX + 0.50000 * pauseBTN.width, pauseBTN.minY + 0.67901 * pauseBTN.height), controlPoint1: CGPointMake(pauseBTN.minX + 0.67901 * pauseBTN.width, pauseBTN.minY + 0.59870 * pauseBTN.height), controlPoint2: CGPointMake(pauseBTN.minX + 0.59871 * pauseBTN.width, pauseBTN.minY + 0.67901 * pauseBTN.height))
        shape3Path.closePath()
        shape3Path.moveToPoint(CGPointMake(pauseBTN.minX + 0.50000 * pauseBTN.width, pauseBTN.minY + 0.32653 * pauseBTN.height))
        shape3Path.addCurveToPoint(CGPointMake(pauseBTN.minX + 0.32651 * pauseBTN.width, pauseBTN.minY + 0.49999 * pauseBTN.height), controlPoint1: CGPointMake(pauseBTN.minX + 0.40434 * pauseBTN.width, pauseBTN.minY + 0.32653 * pauseBTN.height), controlPoint2: CGPointMake(pauseBTN.minX + 0.32651 * pauseBTN.width, pauseBTN.minY + 0.40435 * pauseBTN.height))
        shape3Path.addCurveToPoint(CGPointMake(pauseBTN.minX + 0.50000 * pauseBTN.width, pauseBTN.minY + 0.67347 * pauseBTN.height), controlPoint1: CGPointMake(pauseBTN.minX + 0.32651 * pauseBTN.width, pauseBTN.minY + 0.59564 * pauseBTN.height), controlPoint2: CGPointMake(pauseBTN.minX + 0.40434 * pauseBTN.width, pauseBTN.minY + 0.67347 * pauseBTN.height))
        shape3Path.addCurveToPoint(CGPointMake(pauseBTN.minX + 0.67347 * pauseBTN.width, pauseBTN.minY + 0.49999 * pauseBTN.height), controlPoint1: CGPointMake(pauseBTN.minX + 0.59561 * pauseBTN.width, pauseBTN.minY + 0.67347 * pauseBTN.height), controlPoint2: CGPointMake(pauseBTN.minX + 0.67347 * pauseBTN.width, pauseBTN.minY + 0.59564 * pauseBTN.height))
        shape3Path.addCurveToPoint(CGPointMake(pauseBTN.minX + 0.50000 * pauseBTN.width, pauseBTN.minY + 0.32653 * pauseBTN.height), controlPoint1: CGPointMake(pauseBTN.minX + 0.67347 * pauseBTN.width, pauseBTN.minY + 0.40435 * pauseBTN.height), controlPoint2: CGPointMake(pauseBTN.minX + 0.59561 * pauseBTN.width, pauseBTN.minY + 0.32653 * pauseBTN.height))
        shape3Path.closePath()
        shape3Path.moveToPoint(CGPointMake(pauseBTN.minX + 0.51432 * pauseBTN.width, pauseBTN.minY + 0.45660 * pauseBTN.height))
        shape3Path.addLineToPoint(CGPointMake(pauseBTN.minX + 0.52697 * pauseBTN.width, pauseBTN.minY + 0.45660 * pauseBTN.height))
        shape3Path.addLineToPoint(CGPointMake(pauseBTN.minX + 0.52697 * pauseBTN.width, pauseBTN.minY + 0.54340 * pauseBTN.height))
        shape3Path.addLineToPoint(CGPointMake(pauseBTN.minX + 0.51432 * pauseBTN.width, pauseBTN.minY + 0.54340 * pauseBTN.height))
        shape3Path.addLineToPoint(CGPointMake(pauseBTN.minX + 0.51432 * pauseBTN.width, pauseBTN.minY + 0.45660 * pauseBTN.height))
        shape3Path.closePath()
        shape3Path.moveToPoint(CGPointMake(pauseBTN.minX + 0.47298 * pauseBTN.width, pauseBTN.minY + 0.45660 * pauseBTN.height))
        shape3Path.addLineToPoint(CGPointMake(pauseBTN.minX + 0.48564 * pauseBTN.width, pauseBTN.minY + 0.45660 * pauseBTN.height))
        shape3Path.addLineToPoint(CGPointMake(pauseBTN.minX + 0.48564 * pauseBTN.width, pauseBTN.minY + 0.54340 * pauseBTN.height))
        shape3Path.addLineToPoint(CGPointMake(pauseBTN.minX + 0.47298 * pauseBTN.width, pauseBTN.minY + 0.54340 * pauseBTN.height))
        shape3Path.addLineToPoint(CGPointMake(pauseBTN.minX + 0.47298 * pauseBTN.width, pauseBTN.minY + 0.45660 * pauseBTN.height))
        shape3Path.closePath()
        shape3Path.miterLimit = 100;

        shape3Path.lineCapStyle = kCGLineCapRound;

        shape3Path.lineJoinStyle = kCGLineJoinRound;

        UIColor.whiteColor().setFill()
        shape3Path.fill()
        shape3StrokeColor.setStroke()
        shape3Path.lineWidth = 0.8
        shape3Path.stroke()




        if (pauseBtnClicked) {
            //// PauseBTNClicked
            //// Rectangle 2 Drawing
            let rectangle2Path = UIBezierPath(rect: CGRectMake(pauseBTNClicked.minX + floor(pauseBTNClicked.width * 0.00000 + 0.5), pauseBTNClicked.minY + floor(pauseBTNClicked.height * 0.00000 + 0.5), floor(pauseBTNClicked.width * 1.00000 + 0.5) - floor(pauseBTNClicked.width * 0.00000 + 0.5), floor(pauseBTNClicked.height * 1.00000 + 0.5) - floor(pauseBTNClicked.height * 0.00000 + 0.5)))
            btnClickedColor.setFill()
            rectangle2Path.fill()
            shape3StrokeColor.setStroke()
            rectangle2Path.lineWidth = 0.25
            rectangle2Path.stroke()


            //// shape Drawing
            var shapePath = UIBezierPath()
            shapePath.moveToPoint(CGPointMake(pauseBTNClicked.minX + 0.50000 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.67901 * pauseBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(pauseBTNClicked.minX + 0.32099 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.49999 * pauseBTNClicked.height), controlPoint1: CGPointMake(pauseBTNClicked.minX + 0.40127 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.67901 * pauseBTNClicked.height), controlPoint2: CGPointMake(pauseBTNClicked.minX + 0.32099 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.59870 * pauseBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(pauseBTNClicked.minX + 0.50000 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.32099 * pauseBTNClicked.height), controlPoint1: CGPointMake(pauseBTNClicked.minX + 0.32099 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.40130 * pauseBTNClicked.height), controlPoint2: CGPointMake(pauseBTNClicked.minX + 0.40127 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.32099 * pauseBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(pauseBTNClicked.minX + 0.67901 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.49999 * pauseBTNClicked.height), controlPoint1: CGPointMake(pauseBTNClicked.minX + 0.59871 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.32099 * pauseBTNClicked.height), controlPoint2: CGPointMake(pauseBTNClicked.minX + 0.67901 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.40130 * pauseBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(pauseBTNClicked.minX + 0.50000 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.67901 * pauseBTNClicked.height), controlPoint1: CGPointMake(pauseBTNClicked.minX + 0.67901 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.59870 * pauseBTNClicked.height), controlPoint2: CGPointMake(pauseBTNClicked.minX + 0.59871 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.67901 * pauseBTNClicked.height))
            shapePath.closePath()
            shapePath.moveToPoint(CGPointMake(pauseBTNClicked.minX + 0.50000 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.32653 * pauseBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(pauseBTNClicked.minX + 0.32651 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.49999 * pauseBTNClicked.height), controlPoint1: CGPointMake(pauseBTNClicked.minX + 0.40434 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.32653 * pauseBTNClicked.height), controlPoint2: CGPointMake(pauseBTNClicked.minX + 0.32651 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.40435 * pauseBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(pauseBTNClicked.minX + 0.50000 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.67347 * pauseBTNClicked.height), controlPoint1: CGPointMake(pauseBTNClicked.minX + 0.32651 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.59564 * pauseBTNClicked.height), controlPoint2: CGPointMake(pauseBTNClicked.minX + 0.40434 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.67347 * pauseBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(pauseBTNClicked.minX + 0.67347 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.49999 * pauseBTNClicked.height), controlPoint1: CGPointMake(pauseBTNClicked.minX + 0.59561 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.67347 * pauseBTNClicked.height), controlPoint2: CGPointMake(pauseBTNClicked.minX + 0.67347 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.59564 * pauseBTNClicked.height))
            shapePath.addCurveToPoint(CGPointMake(pauseBTNClicked.minX + 0.50000 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.32653 * pauseBTNClicked.height), controlPoint1: CGPointMake(pauseBTNClicked.minX + 0.67347 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.40435 * pauseBTNClicked.height), controlPoint2: CGPointMake(pauseBTNClicked.minX + 0.59561 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.32653 * pauseBTNClicked.height))
            shapePath.closePath()
            shapePath.moveToPoint(CGPointMake(pauseBTNClicked.minX + 0.51432 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.45660 * pauseBTNClicked.height))
            shapePath.addLineToPoint(CGPointMake(pauseBTNClicked.minX + 0.52697 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.45660 * pauseBTNClicked.height))
            shapePath.addLineToPoint(CGPointMake(pauseBTNClicked.minX + 0.52697 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.54340 * pauseBTNClicked.height))
            shapePath.addLineToPoint(CGPointMake(pauseBTNClicked.minX + 0.51432 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.54340 * pauseBTNClicked.height))
            shapePath.addLineToPoint(CGPointMake(pauseBTNClicked.minX + 0.51432 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.45660 * pauseBTNClicked.height))
            shapePath.closePath()
            shapePath.moveToPoint(CGPointMake(pauseBTNClicked.minX + 0.47298 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.45660 * pauseBTNClicked.height))
            shapePath.addLineToPoint(CGPointMake(pauseBTNClicked.minX + 0.48564 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.45660 * pauseBTNClicked.height))
            shapePath.addLineToPoint(CGPointMake(pauseBTNClicked.minX + 0.48564 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.54340 * pauseBTNClicked.height))
            shapePath.addLineToPoint(CGPointMake(pauseBTNClicked.minX + 0.47298 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.54340 * pauseBTNClicked.height))
            shapePath.addLineToPoint(CGPointMake(pauseBTNClicked.minX + 0.47298 * pauseBTNClicked.width, pauseBTNClicked.minY + 0.45660 * pauseBTNClicked.height))
            shapePath.closePath()
            shapePath.miterLimit = 100;

            shapePath.lineCapStyle = kCGLineCapRound;

            shapePath.lineJoinStyle = kCGLineJoinRound;

            iconClickedColor.setFill()
            shapePath.fill()
            iconClickedColor.setStroke()
            shapePath.lineWidth = 0.8
            shapePath.stroke()


        }


        if (channelState) {
            //// PlayBTN
            if (channelState) {
                //// Rectangle 3 Drawing
                let rectangle3Path = UIBezierPath(rect: CGRectMake(playBTN.minX + floor(playBTN.width * 0.00000 + 0.5), playBTN.minY + floor(playBTN.height * 0.00000 + 0.5), floor(playBTN.width * 1.00000 + 0.5) - floor(playBTN.width * 0.00000 + 0.5), floor(playBTN.height * 1.00000 + 0.5) - floor(playBTN.height * 0.00000 + 0.5)))
                red.setFill()
                rectangle3Path.fill()
                shape3StrokeColor.setStroke()
                rectangle3Path.lineWidth = 0.25
                rectangle3Path.stroke()
            }


            //// Shape 4 Drawing
            var shape4Path = UIBezierPath()
            shape4Path.moveToPoint(CGPointMake(playBTN.minX + 0.46969 * playBTN.width, playBTN.minY + 0.56212 * playBTN.height))
            shape4Path.addLineToPoint(CGPointMake(playBTN.minX + 0.46969 * playBTN.width, playBTN.minY + 0.43792 * playBTN.height))
            shape4Path.addLineToPoint(CGPointMake(playBTN.minX + 0.55618 * playBTN.width, playBTN.minY + 0.50000 * playBTN.height))
            shape4Path.addLineToPoint(CGPointMake(playBTN.minX + 0.46969 * playBTN.width, playBTN.minY + 0.56212 * playBTN.height))
            shape4Path.closePath()
            shape4Path.moveToPoint(CGPointMake(playBTN.minX + 0.47525 * playBTN.width, playBTN.minY + 0.44872 * playBTN.height))
            shape4Path.addLineToPoint(CGPointMake(playBTN.minX + 0.47525 * playBTN.width, playBTN.minY + 0.55132 * playBTN.height))
            shape4Path.addLineToPoint(CGPointMake(playBTN.minX + 0.54666 * playBTN.width, playBTN.minY + 0.50000 * playBTN.height))
            shape4Path.addLineToPoint(CGPointMake(playBTN.minX + 0.47525 * playBTN.width, playBTN.minY + 0.44872 * playBTN.height))
            shape4Path.closePath()
            shape4Path.moveToPoint(CGPointMake(playBTN.minX + 0.50000 * playBTN.width, playBTN.minY + 0.67901 * playBTN.height))
            shape4Path.addCurveToPoint(CGPointMake(playBTN.minX + 0.32099 * playBTN.width, playBTN.minY + 0.50000 * playBTN.height), controlPoint1: CGPointMake(playBTN.minX + 0.40127 * playBTN.width, playBTN.minY + 0.67901 * playBTN.height), controlPoint2: CGPointMake(playBTN.minX + 0.32099 * playBTN.width, playBTN.minY + 0.59873 * playBTN.height))
            shape4Path.addCurveToPoint(CGPointMake(playBTN.minX + 0.50000 * playBTN.width, playBTN.minY + 0.32099 * playBTN.height), controlPoint1: CGPointMake(playBTN.minX + 0.32099 * playBTN.width, playBTN.minY + 0.40131 * playBTN.height), controlPoint2: CGPointMake(playBTN.minX + 0.40127 * playBTN.width, playBTN.minY + 0.32099 * playBTN.height))
            shape4Path.addCurveToPoint(CGPointMake(playBTN.minX + 0.67901 * playBTN.width, playBTN.minY + 0.50000 * playBTN.height), controlPoint1: CGPointMake(playBTN.minX + 0.59871 * playBTN.width, playBTN.minY + 0.32099 * playBTN.height), controlPoint2: CGPointMake(playBTN.minX + 0.67901 * playBTN.width, playBTN.minY + 0.40131 * playBTN.height))
            shape4Path.addCurveToPoint(CGPointMake(playBTN.minX + 0.50000 * playBTN.width, playBTN.minY + 0.67901 * playBTN.height), controlPoint1: CGPointMake(playBTN.minX + 0.67901 * playBTN.width, playBTN.minY + 0.59873 * playBTN.height), controlPoint2: CGPointMake(playBTN.minX + 0.59871 * playBTN.width, playBTN.minY + 0.67901 * playBTN.height))
            shape4Path.closePath()
            shape4Path.moveToPoint(CGPointMake(playBTN.minX + 0.50000 * playBTN.width, playBTN.minY + 0.32653 * playBTN.height))
            shape4Path.addCurveToPoint(CGPointMake(playBTN.minX + 0.32653 * playBTN.width, playBTN.minY + 0.50000 * playBTN.height), controlPoint1: CGPointMake(playBTN.minX + 0.40434 * playBTN.width, playBTN.minY + 0.32653 * playBTN.height), controlPoint2: CGPointMake(playBTN.minX + 0.32653 * playBTN.width, playBTN.minY + 0.40436 * playBTN.height))
            shape4Path.addCurveToPoint(CGPointMake(playBTN.minX + 0.50000 * playBTN.width, playBTN.minY + 0.67349 * playBTN.height), controlPoint1: CGPointMake(playBTN.minX + 0.32653 * playBTN.width, playBTN.minY + 0.59566 * playBTN.height), controlPoint2: CGPointMake(playBTN.minX + 0.40434 * playBTN.width, playBTN.minY + 0.67349 * playBTN.height))
            shape4Path.addCurveToPoint(CGPointMake(playBTN.minX + 0.67347 * playBTN.width, playBTN.minY + 0.50000 * playBTN.height), controlPoint1: CGPointMake(playBTN.minX + 0.59564 * playBTN.width, playBTN.minY + 0.67349 * playBTN.height), controlPoint2: CGPointMake(playBTN.minX + 0.67347 * playBTN.width, playBTN.minY + 0.59566 * playBTN.height))
            shape4Path.addCurveToPoint(CGPointMake(playBTN.minX + 0.50000 * playBTN.width, playBTN.minY + 0.32653 * playBTN.height), controlPoint1: CGPointMake(playBTN.minX + 0.67347 * playBTN.width, playBTN.minY + 0.40436 * playBTN.height), controlPoint2: CGPointMake(playBTN.minX + 0.59564 * playBTN.width, playBTN.minY + 0.32653 * playBTN.height))
            shape4Path.closePath()
            shape4Path.miterLimit = 100;

            shape4Path.lineCapStyle = kCGLineCapRound;

            shape4Path.lineJoinStyle = kCGLineJoinRound;

            shape4Color.setFill()
            shape4Path.fill()
            shape4StrokeColor.setStroke()
            shape4Path.lineWidth = 0.8
            shape4Path.stroke()


        }


        if (playBtnClicked) {
            //// PlayBTNClicked
            //// Rectangle 4 Drawing
            let rectangle4Path = UIBezierPath(rect: CGRectMake(playBTNClicked.minX + floor(playBTNClicked.width * 0.00000 + 0.5), playBTNClicked.minY + floor(playBTNClicked.height * 0.00000 + 0.5), floor(playBTNClicked.width * 1.00000 + 0.5) - floor(playBTNClicked.width * 0.00000 + 0.5), floor(playBTNClicked.height * 1.00000 + 0.5) - floor(playBTNClicked.height * 0.00000 + 0.5)))
            btnClickedColor.setFill()
            rectangle4Path.fill()
            shape3StrokeColor.setStroke()
            rectangle4Path.lineWidth = 0.25
            rectangle4Path.stroke()


            //// Shape 5 Drawing
            var shape5Path = UIBezierPath()
            shape5Path.moveToPoint(CGPointMake(playBTNClicked.minX + 0.46969 * playBTNClicked.width, playBTNClicked.minY + 0.56212 * playBTNClicked.height))
            shape5Path.addLineToPoint(CGPointMake(playBTNClicked.minX + 0.46969 * playBTNClicked.width, playBTNClicked.minY + 0.43792 * playBTNClicked.height))
            shape5Path.addLineToPoint(CGPointMake(playBTNClicked.minX + 0.55618 * playBTNClicked.width, playBTNClicked.minY + 0.50000 * playBTNClicked.height))
            shape5Path.addLineToPoint(CGPointMake(playBTNClicked.minX + 0.46969 * playBTNClicked.width, playBTNClicked.minY + 0.56212 * playBTNClicked.height))
            shape5Path.closePath()
            shape5Path.moveToPoint(CGPointMake(playBTNClicked.minX + 0.47525 * playBTNClicked.width, playBTNClicked.minY + 0.44872 * playBTNClicked.height))
            shape5Path.addLineToPoint(CGPointMake(playBTNClicked.minX + 0.47525 * playBTNClicked.width, playBTNClicked.minY + 0.55132 * playBTNClicked.height))
            shape5Path.addLineToPoint(CGPointMake(playBTNClicked.minX + 0.54666 * playBTNClicked.width, playBTNClicked.minY + 0.50000 * playBTNClicked.height))
            shape5Path.addLineToPoint(CGPointMake(playBTNClicked.minX + 0.47525 * playBTNClicked.width, playBTNClicked.minY + 0.44872 * playBTNClicked.height))
            shape5Path.closePath()
            shape5Path.moveToPoint(CGPointMake(playBTNClicked.minX + 0.50000 * playBTNClicked.width, playBTNClicked.minY + 0.67901 * playBTNClicked.height))
            shape5Path.addCurveToPoint(CGPointMake(playBTNClicked.minX + 0.32099 * playBTNClicked.width, playBTNClicked.minY + 0.50000 * playBTNClicked.height), controlPoint1: CGPointMake(playBTNClicked.minX + 0.40127 * playBTNClicked.width, playBTNClicked.minY + 0.67901 * playBTNClicked.height), controlPoint2: CGPointMake(playBTNClicked.minX + 0.32099 * playBTNClicked.width, playBTNClicked.minY + 0.59873 * playBTNClicked.height))
            shape5Path.addCurveToPoint(CGPointMake(playBTNClicked.minX + 0.50000 * playBTNClicked.width, playBTNClicked.minY + 0.32099 * playBTNClicked.height), controlPoint1: CGPointMake(playBTNClicked.minX + 0.32099 * playBTNClicked.width, playBTNClicked.minY + 0.40131 * playBTNClicked.height), controlPoint2: CGPointMake(playBTNClicked.minX + 0.40127 * playBTNClicked.width, playBTNClicked.minY + 0.32099 * playBTNClicked.height))
            shape5Path.addCurveToPoint(CGPointMake(playBTNClicked.minX + 0.67901 * playBTNClicked.width, playBTNClicked.minY + 0.50000 * playBTNClicked.height), controlPoint1: CGPointMake(playBTNClicked.minX + 0.59871 * playBTNClicked.width, playBTNClicked.minY + 0.32099 * playBTNClicked.height), controlPoint2: CGPointMake(playBTNClicked.minX + 0.67901 * playBTNClicked.width, playBTNClicked.minY + 0.40131 * playBTNClicked.height))
            shape5Path.addCurveToPoint(CGPointMake(playBTNClicked.minX + 0.50000 * playBTNClicked.width, playBTNClicked.minY + 0.67901 * playBTNClicked.height), controlPoint1: CGPointMake(playBTNClicked.minX + 0.67901 * playBTNClicked.width, playBTNClicked.minY + 0.59873 * playBTNClicked.height), controlPoint2: CGPointMake(playBTNClicked.minX + 0.59871 * playBTNClicked.width, playBTNClicked.minY + 0.67901 * playBTNClicked.height))
            shape5Path.closePath()
            shape5Path.moveToPoint(CGPointMake(playBTNClicked.minX + 0.50000 * playBTNClicked.width, playBTNClicked.minY + 0.32653 * playBTNClicked.height))
            shape5Path.addCurveToPoint(CGPointMake(playBTNClicked.minX + 0.32653 * playBTNClicked.width, playBTNClicked.minY + 0.50000 * playBTNClicked.height), controlPoint1: CGPointMake(playBTNClicked.minX + 0.40434 * playBTNClicked.width, playBTNClicked.minY + 0.32653 * playBTNClicked.height), controlPoint2: CGPointMake(playBTNClicked.minX + 0.32653 * playBTNClicked.width, playBTNClicked.minY + 0.40436 * playBTNClicked.height))
            shape5Path.addCurveToPoint(CGPointMake(playBTNClicked.minX + 0.50000 * playBTNClicked.width, playBTNClicked.minY + 0.67349 * playBTNClicked.height), controlPoint1: CGPointMake(playBTNClicked.minX + 0.32653 * playBTNClicked.width, playBTNClicked.minY + 0.59566 * playBTNClicked.height), controlPoint2: CGPointMake(playBTNClicked.minX + 0.40434 * playBTNClicked.width, playBTNClicked.minY + 0.67349 * playBTNClicked.height))
            shape5Path.addCurveToPoint(CGPointMake(playBTNClicked.minX + 0.67347 * playBTNClicked.width, playBTNClicked.minY + 0.50000 * playBTNClicked.height), controlPoint1: CGPointMake(playBTNClicked.minX + 0.59564 * playBTNClicked.width, playBTNClicked.minY + 0.67349 * playBTNClicked.height), controlPoint2: CGPointMake(playBTNClicked.minX + 0.67347 * playBTNClicked.width, playBTNClicked.minY + 0.59566 * playBTNClicked.height))
            shape5Path.addCurveToPoint(CGPointMake(playBTNClicked.minX + 0.50000 * playBTNClicked.width, playBTNClicked.minY + 0.32653 * playBTNClicked.height), controlPoint1: CGPointMake(playBTNClicked.minX + 0.67347 * playBTNClicked.width, playBTNClicked.minY + 0.40436 * playBTNClicked.height), controlPoint2: CGPointMake(playBTNClicked.minX + 0.59564 * playBTNClicked.width, playBTNClicked.minY + 0.32653 * playBTNClicked.height))
            shape5Path.closePath()
            shape5Path.miterLimit = 100;

            shape5Path.lineCapStyle = kCGLineCapRound;

            shape5Path.lineJoinStyle = kCGLineJoinRound;

            iconClickedColor.setFill()
            shape5Path.fill()
            iconClickedColor.setStroke()
            shape5Path.lineWidth = 0.8
            shape5Path.stroke()


        }
    }

}


