//
//  WeshappSelectedCellSK.swift
//  Weshapp
//
//  Created by SM on 12/03/2015.
//  Copyright (c) 2015 Weshapp. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class WeshappSelectedCellSK : NSObject {

    //// Drawing Methods

    public class func drawSelectedCell(#frame: CGRect, btnClicked: Bool, notClicked: Bool) {
        //// Color Declarations
        let btnColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let btnClickedColor = UIColor(red: 0.914, green: 0.945, blue: 0.949, alpha: 1.000)

        if (notClicked) {
            //// btn Drawing
            var btnPath = UIBezierPath()
            btnPath.moveToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + -0.00000 * frame.height))
            btnPath.addLineToPoint(CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + -0.00000 * frame.height))
            btnPath.addLineToPoint(CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + 1.00000 * frame.height))
            btnPath.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 1.00000 * frame.height))
            btnPath.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + -0.00000 * frame.height))
            btnPath.closePath()
            btnColor.setFill()
            btnPath.fill()
        }


        if (btnClicked) {
            //// Clicked Drawing
            var clickedPath = UIBezierPath()
            clickedPath.moveToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + -0.00000 * frame.height))
            clickedPath.addLineToPoint(CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + -0.00000 * frame.height))
            clickedPath.addLineToPoint(CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + 1.00000 * frame.height))
            clickedPath.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 1.00000 * frame.height))
            clickedPath.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + -0.00000 * frame.height))
            clickedPath.closePath()
            btnClickedColor.setFill()
            clickedPath.fill()
        }
    }

}

