//
//  WeshappSK.swift
//  Weshapp
//
//  Created by SM on 22/01/2015.
//  Copyright (c) 2015 OutOfAxis. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class WeshappSK : NSObject {

    //// Drawing Methods

    public class func drawCanvas1(#frame: CGRect, btnClicked: Bool) {
        //// Color Declarations
        let btnColor = UIColor(red: 1.000, green: 0.349, blue: 0.349, alpha: 1.000)
        let arrowPickColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let arrowLineColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let btnClickedColor = UIColor(red: 0.888, green: 0.290, blue: 0.290, alpha: 1.000)


        //// Subframes
        let frame2 = CGRectMake(frame.minX + floor(frame.width * 0.41600 + 0.5), frame.minY + floor(frame.height * 0.00000 + 0.5), floor(frame.width * 0.57600 + 0.5) - floor(frame.width * 0.41600 + 0.5), floor(frame.height * 1.00000 + 0.5) - floor(frame.height * 0.00000 + 0.5))


        //// button Drawing
        var buttonPath = UIBezierPath()
        buttonPath.moveToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + -0.00000 * frame.height))
        buttonPath.addLineToPoint(CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + -0.00000 * frame.height))
        buttonPath.addLineToPoint(CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + 1.00000 * frame.height))
        buttonPath.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 1.00000 * frame.height))
        buttonPath.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + -0.00000 * frame.height))
        buttonPath.closePath()
        btnColor.setFill()
        buttonPath.fill()


        if (btnClicked) {
            //// button 2 Drawing
            var button2Path = UIBezierPath()
            button2Path.moveToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + -0.00000 * frame.height))
            button2Path.addLineToPoint(CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + -0.00000 * frame.height))
            button2Path.addLineToPoint(CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + 1.00000 * frame.height))
            button2Path.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 1.00000 * frame.height))
            button2Path.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + -0.00000 * frame.height))
            button2Path.closePath()
            btnClickedColor.setFill()
            button2Path.fill()
        }


        //// Arrow Pick Drawing
        var arrowPickPath = UIBezierPath()
        arrowPickPath.moveToPoint(CGPointMake(frame2.minX + 0.52533 * frame2.width, frame2.minY + 0.32307 * frame2.height))
        arrowPickPath.addLineToPoint(CGPointMake(frame2.minX + 0.69200 * frame2.width, frame2.minY + 0.50253 * frame2.height))
        arrowPickPath.addLineToPoint(CGPointMake(frame2.minX + 0.67533 * frame2.width, frame2.minY + 0.52048 * frame2.height))
        arrowPickPath.addLineToPoint(CGPointMake(frame2.minX + 0.50867 * frame2.width, frame2.minY + 0.34102 * frame2.height))
        arrowPickPath.addLineToPoint(CGPointMake(frame2.minX + 0.52533 * frame2.width, frame2.minY + 0.32307 * frame2.height))
        arrowPickPath.closePath()
        arrowPickPath.moveToPoint(CGPointMake(frame2.minX + 0.50867 * frame2.width, frame2.minY + 0.67172 * frame2.height))
        arrowPickPath.addLineToPoint(CGPointMake(frame2.minX + 0.67533 * frame2.width, frame2.minY + 0.49227 * frame2.height))
        arrowPickPath.addLineToPoint(CGPointMake(frame2.minX + 0.69200 * frame2.width, frame2.minY + 0.51021 * frame2.height))
        arrowPickPath.addLineToPoint(CGPointMake(frame2.minX + 0.52533 * frame2.width, frame2.minY + 0.68967 * frame2.height))
        arrowPickPath.addLineToPoint(CGPointMake(frame2.minX + 0.50867 * frame2.width, frame2.minY + 0.67172 * frame2.height))
        arrowPickPath.closePath()
        arrowPickColor.setFill()
        arrowPickPath.fill()


        //// Arrow Line Drawing
        var arrowLinePath = UIBezierPath()
        arrowLinePath.moveToPoint(CGPointMake(frame2.minX + 0.66005 * frame2.width, frame2.minY + 0.49368 * frame2.height))
        arrowLinePath.addLineToPoint(CGPointMake(frame2.minX + 0.36005 * frame2.width, frame2.minY + 0.49368 * frame2.height))
        arrowLinePath.addLineToPoint(CGPointMake(frame2.minX + 0.36005 * frame2.width, frame2.minY + 0.51868 * frame2.height))
        arrowLinePath.addLineToPoint(CGPointMake(frame2.minX + 0.66005 * frame2.width, frame2.minY + 0.51868 * frame2.height))
        arrowLinePath.addLineToPoint(CGPointMake(frame2.minX + 0.66005 * frame2.width, frame2.minY + 0.49368 * frame2.height))
        arrowLinePath.closePath()
        arrowLineColor.setFill()
        arrowLinePath.fill()
    }

}

