//
//  WeshappSmileIconSK.swift
//  Weshapp
//
//  Created by SM on 20/02/2015.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class WeshappSmileIconSK : NSObject {

    //// Drawing Methods

    public class func drawSmileyIcon(#frame: CGRect, smlClicked: Bool, smlNotClicked: Bool) {
        //// Color Declarations
        let smileyColor = UIColor(red: 0.863, green: 0.341, blue: 0.326, alpha: 1.000)
        let smileyClickedColor = UIColor(red: 0.890, green: 0.290, blue: 0.290, alpha: 1.000)

        if (smlNotClicked) {
            //// Smiley Drawing
            var smileyPath = UIBezierPath()
            smileyPath.moveToPoint(CGPointMake(frame.minX + 0.49949 * frame.width, frame.minY + 0.06489 * frame.height))
            smileyPath.addCurveToPoint(CGPointMake(frame.minX + 0.93208 * frame.width, frame.minY + 0.49747 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.73802 * frame.width, frame.minY + 0.06489 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.93208 * frame.width, frame.minY + 0.25895 * frame.height))
            smileyPath.addCurveToPoint(CGPointMake(frame.minX + 0.49949 * frame.width, frame.minY + 0.93005 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.93208 * frame.width, frame.minY + 0.73597 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.73802 * frame.width, frame.minY + 0.93005 * frame.height))
            smileyPath.addCurveToPoint(CGPointMake(frame.minX + 0.06692 * frame.width, frame.minY + 0.49747 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.26098 * frame.width, frame.minY + 0.93005 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.06692 * frame.width, frame.minY + 0.73597 * frame.height))
            smileyPath.addCurveToPoint(CGPointMake(frame.minX + 0.49949 * frame.width, frame.minY + 0.06489 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.06692 * frame.width, frame.minY + 0.25895 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.26098 * frame.width, frame.minY + 0.06489 * frame.height))
            smileyPath.addLineToPoint(CGPointMake(frame.minX + 0.49949 * frame.width, frame.minY + 0.06489 * frame.height))
            smileyPath.closePath()
            smileyPath.moveToPoint(CGPointMake(frame.minX + 0.49949 * frame.width, frame.minY + 0.00874 * frame.height))
            smileyPath.addCurveToPoint(CGPointMake(frame.minX + 0.01078 * frame.width, frame.minY + 0.49747 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.22958 * frame.width, frame.minY + 0.00874 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.01078 * frame.width, frame.minY + 0.22754 * frame.height))
            smileyPath.addCurveToPoint(CGPointMake(frame.minX + 0.49949 * frame.width, frame.minY + 0.98619 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.01078 * frame.width, frame.minY + 0.76739 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.22958 * frame.width, frame.minY + 0.98619 * frame.height))
            smileyPath.addCurveToPoint(CGPointMake(frame.minX + 0.98822 * frame.width, frame.minY + 0.49747 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.76941 * frame.width, frame.minY + 0.98619 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.98822 * frame.width, frame.minY + 0.76739 * frame.height))
            smileyPath.addCurveToPoint(CGPointMake(frame.minX + 0.49949 * frame.width, frame.minY + 0.00874 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.98822 * frame.width, frame.minY + 0.22754 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.76941 * frame.width, frame.minY + 0.00874 * frame.height))
            smileyPath.addLineToPoint(CGPointMake(frame.minX + 0.49949 * frame.width, frame.minY + 0.00874 * frame.height))
            smileyPath.closePath()
            smileyPath.moveToPoint(CGPointMake(frame.minX + 0.59965 * frame.width, frame.minY + 0.40456 * frame.height))
            smileyPath.addCurveToPoint(CGPointMake(frame.minX + 0.67424 * frame.width, frame.minY + 0.47916 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.59965 * frame.width, frame.minY + 0.44576 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.63304 * frame.width, frame.minY + 0.47916 * frame.height))
            smileyPath.addCurveToPoint(CGPointMake(frame.minX + 0.74883 * frame.width, frame.minY + 0.40456 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.71543 * frame.width, frame.minY + 0.47916 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.74883 * frame.width, frame.minY + 0.44576 * frame.height))
            smileyPath.addCurveToPoint(CGPointMake(frame.minX + 0.67424 * frame.width, frame.minY + 0.32999 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.74883 * frame.width, frame.minY + 0.36336 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.71543 * frame.width, frame.minY + 0.32999 * frame.height))
            smileyPath.addCurveToPoint(CGPointMake(frame.minX + 0.59965 * frame.width, frame.minY + 0.40456 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.63304 * frame.width, frame.minY + 0.32999 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.59965 * frame.width, frame.minY + 0.36336 * frame.height))
            smileyPath.closePath()
            smileyPath.moveToPoint(CGPointMake(frame.minX + 0.25016 * frame.width, frame.minY + 0.40456 * frame.height))
            smileyPath.addCurveToPoint(CGPointMake(frame.minX + 0.32475 * frame.width, frame.minY + 0.47916 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.25016 * frame.width, frame.minY + 0.44576 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.28354 * frame.width, frame.minY + 0.47916 * frame.height))
            smileyPath.addCurveToPoint(CGPointMake(frame.minX + 0.39934 * frame.width, frame.minY + 0.40456 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.36595 * frame.width, frame.minY + 0.47916 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.39934 * frame.width, frame.minY + 0.44576 * frame.height))
            smileyPath.addCurveToPoint(CGPointMake(frame.minX + 0.32475 * frame.width, frame.minY + 0.32999 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.39934 * frame.width, frame.minY + 0.36336 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.36595 * frame.width, frame.minY + 0.32999 * frame.height))
            smileyPath.addCurveToPoint(CGPointMake(frame.minX + 0.25016 * frame.width, frame.minY + 0.40456 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.28354 * frame.width, frame.minY + 0.32999 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.25016 * frame.width, frame.minY + 0.36336 * frame.height))
            smileyPath.closePath()
            smileyPath.moveToPoint(CGPointMake(frame.minX + 0.26768 * frame.width, frame.minY + 0.60911 * frame.height))
            smileyPath.addCurveToPoint(CGPointMake(frame.minX + 0.28963 * frame.width, frame.minY + 0.67203 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.25663 * frame.width, frame.minY + 0.62910 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.26599 * frame.width, frame.minY + 0.65878 * frame.height))
            smileyPath.addCurveToPoint(CGPointMake(frame.minX + 0.70935 * frame.width, frame.minY + 0.67203 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.42216 * frame.width, frame.minY + 0.77785 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.57684 * frame.width, frame.minY + 0.77217 * frame.height))
            smileyPath.addCurveToPoint(CGPointMake(frame.minX + 0.73130 * frame.width, frame.minY + 0.60911 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.73302 * frame.width, frame.minY + 0.65876 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.74235 * frame.width, frame.minY + 0.62910 * frame.height))
            smileyPath.addLineToPoint(CGPointMake(frame.minX + 0.73130 * frame.width, frame.minY + 0.60911 * frame.height))
            smileyPath.addCurveToPoint(CGPointMake(frame.minX + 0.67686 * frame.width, frame.minY + 0.59455 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.72024 * frame.width, frame.minY + 0.58904 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.69626 * frame.width, frame.minY + 0.58374 * frame.height))
            smileyPath.addCurveToPoint(CGPointMake(frame.minX + 0.32213 * frame.width, frame.minY + 0.59455 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.55176 * frame.width, frame.minY + 0.68875 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.42157 * frame.width, frame.minY + 0.67371 * frame.height))
            smileyPath.addCurveToPoint(CGPointMake(frame.minX + 0.26768 * frame.width, frame.minY + 0.60911 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.30275 * frame.width, frame.minY + 0.58374 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.27877 * frame.width, frame.minY + 0.58902 * frame.height))
            smileyPath.addLineToPoint(CGPointMake(frame.minX + 0.26768 * frame.width, frame.minY + 0.60911 * frame.height))
            smileyPath.closePath()
            smileyColor.setFill()
            smileyPath.fill()
        }


        if (smlClicked) {
            //// SmileyClicked Drawing
            var smileyClickedPath = UIBezierPath()
            smileyClickedPath.moveToPoint(CGPointMake(frame.minX + 0.49949 * frame.width, frame.minY + 0.06489 * frame.height))
            smileyClickedPath.addCurveToPoint(CGPointMake(frame.minX + 0.93208 * frame.width, frame.minY + 0.49747 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.73802 * frame.width, frame.minY + 0.06489 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.93208 * frame.width, frame.minY + 0.25895 * frame.height))
            smileyClickedPath.addCurveToPoint(CGPointMake(frame.minX + 0.49949 * frame.width, frame.minY + 0.93005 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.93208 * frame.width, frame.minY + 0.73597 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.73802 * frame.width, frame.minY + 0.93005 * frame.height))
            smileyClickedPath.addCurveToPoint(CGPointMake(frame.minX + 0.06692 * frame.width, frame.minY + 0.49747 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.26098 * frame.width, frame.minY + 0.93005 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.06692 * frame.width, frame.minY + 0.73597 * frame.height))
            smileyClickedPath.addCurveToPoint(CGPointMake(frame.minX + 0.49949 * frame.width, frame.minY + 0.06489 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.06692 * frame.width, frame.minY + 0.25895 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.26098 * frame.width, frame.minY + 0.06489 * frame.height))
            smileyClickedPath.addLineToPoint(CGPointMake(frame.minX + 0.49949 * frame.width, frame.minY + 0.06489 * frame.height))
            smileyClickedPath.closePath()
            smileyClickedPath.moveToPoint(CGPointMake(frame.minX + 0.49949 * frame.width, frame.minY + 0.00874 * frame.height))
            smileyClickedPath.addCurveToPoint(CGPointMake(frame.minX + 0.01078 * frame.width, frame.minY + 0.49747 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.22958 * frame.width, frame.minY + 0.00874 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.01078 * frame.width, frame.minY + 0.22754 * frame.height))
            smileyClickedPath.addCurveToPoint(CGPointMake(frame.minX + 0.49949 * frame.width, frame.minY + 0.98619 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.01078 * frame.width, frame.minY + 0.76739 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.22958 * frame.width, frame.minY + 0.98619 * frame.height))
            smileyClickedPath.addCurveToPoint(CGPointMake(frame.minX + 0.98822 * frame.width, frame.minY + 0.49747 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.76941 * frame.width, frame.minY + 0.98619 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.98822 * frame.width, frame.minY + 0.76739 * frame.height))
            smileyClickedPath.addCurveToPoint(CGPointMake(frame.minX + 0.49949 * frame.width, frame.minY + 0.00874 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.98822 * frame.width, frame.minY + 0.22754 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.76941 * frame.width, frame.minY + 0.00874 * frame.height))
            smileyClickedPath.addLineToPoint(CGPointMake(frame.minX + 0.49949 * frame.width, frame.minY + 0.00874 * frame.height))
            smileyClickedPath.closePath()
            smileyClickedPath.moveToPoint(CGPointMake(frame.minX + 0.59965 * frame.width, frame.minY + 0.40456 * frame.height))
            smileyClickedPath.addCurveToPoint(CGPointMake(frame.minX + 0.67424 * frame.width, frame.minY + 0.47916 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.59965 * frame.width, frame.minY + 0.44576 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.63304 * frame.width, frame.minY + 0.47916 * frame.height))
            smileyClickedPath.addCurveToPoint(CGPointMake(frame.minX + 0.74883 * frame.width, frame.minY + 0.40456 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.71543 * frame.width, frame.minY + 0.47916 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.74883 * frame.width, frame.minY + 0.44576 * frame.height))
            smileyClickedPath.addCurveToPoint(CGPointMake(frame.minX + 0.67424 * frame.width, frame.minY + 0.32999 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.74883 * frame.width, frame.minY + 0.36336 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.71543 * frame.width, frame.minY + 0.32999 * frame.height))
            smileyClickedPath.addCurveToPoint(CGPointMake(frame.minX + 0.59965 * frame.width, frame.minY + 0.40456 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.63304 * frame.width, frame.minY + 0.32999 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.59965 * frame.width, frame.minY + 0.36336 * frame.height))
            smileyClickedPath.closePath()
            smileyClickedPath.moveToPoint(CGPointMake(frame.minX + 0.25016 * frame.width, frame.minY + 0.40456 * frame.height))
            smileyClickedPath.addCurveToPoint(CGPointMake(frame.minX + 0.32475 * frame.width, frame.minY + 0.47916 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.25016 * frame.width, frame.minY + 0.44576 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.28354 * frame.width, frame.minY + 0.47916 * frame.height))
            smileyClickedPath.addCurveToPoint(CGPointMake(frame.minX + 0.39934 * frame.width, frame.minY + 0.40456 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.36595 * frame.width, frame.minY + 0.47916 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.39934 * frame.width, frame.minY + 0.44576 * frame.height))
            smileyClickedPath.addCurveToPoint(CGPointMake(frame.minX + 0.32475 * frame.width, frame.minY + 0.32999 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.39934 * frame.width, frame.minY + 0.36336 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.36595 * frame.width, frame.minY + 0.32999 * frame.height))
            smileyClickedPath.addCurveToPoint(CGPointMake(frame.minX + 0.25016 * frame.width, frame.minY + 0.40456 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.28354 * frame.width, frame.minY + 0.32999 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.25016 * frame.width, frame.minY + 0.36336 * frame.height))
            smileyClickedPath.closePath()
            smileyClickedPath.moveToPoint(CGPointMake(frame.minX + 0.26768 * frame.width, frame.minY + 0.60911 * frame.height))
            smileyClickedPath.addCurveToPoint(CGPointMake(frame.minX + 0.28963 * frame.width, frame.minY + 0.67203 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.25663 * frame.width, frame.minY + 0.62910 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.26599 * frame.width, frame.minY + 0.65878 * frame.height))
            smileyClickedPath.addCurveToPoint(CGPointMake(frame.minX + 0.70935 * frame.width, frame.minY + 0.67203 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.42216 * frame.width, frame.minY + 0.77785 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.57684 * frame.width, frame.minY + 0.77217 * frame.height))
            smileyClickedPath.addCurveToPoint(CGPointMake(frame.minX + 0.73130 * frame.width, frame.minY + 0.60911 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.73302 * frame.width, frame.minY + 0.65876 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.74235 * frame.width, frame.minY + 0.62910 * frame.height))
            smileyClickedPath.addLineToPoint(CGPointMake(frame.minX + 0.73130 * frame.width, frame.minY + 0.60911 * frame.height))
            smileyClickedPath.addCurveToPoint(CGPointMake(frame.minX + 0.67686 * frame.width, frame.minY + 0.59455 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.72024 * frame.width, frame.minY + 0.58904 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.69626 * frame.width, frame.minY + 0.58374 * frame.height))
            smileyClickedPath.addCurveToPoint(CGPointMake(frame.minX + 0.32213 * frame.width, frame.minY + 0.59455 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.55176 * frame.width, frame.minY + 0.68875 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.42157 * frame.width, frame.minY + 0.67371 * frame.height))
            smileyClickedPath.addCurveToPoint(CGPointMake(frame.minX + 0.26768 * frame.width, frame.minY + 0.60911 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.30275 * frame.width, frame.minY + 0.58374 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.27877 * frame.width, frame.minY + 0.58902 * frame.height))
            smileyClickedPath.addLineToPoint(CGPointMake(frame.minX + 0.26768 * frame.width, frame.minY + 0.60911 * frame.height))
            smileyClickedPath.closePath()
            smileyClickedColor.setFill()
            smileyClickedPath.fill()
        }
    }

}

