//
//  WeshappListArrowSK.swift
//  Weshapp
//
//  Created by SM on 07/02/2015.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class WeshappListArrowSK : NSObject {

    //// Drawing Methods

    public class func drawLinkArrowCanvas(#arrowFrame: CGRect) {
        //// Color Declarations
        let arrowColor = UIColor(red: 0.956, green: 0.470, blue: 0.488, alpha: 1.000)


        //// Subframes
        let group2: CGRect = CGRectMake(arrowFrame.minX + floor(arrowFrame.width * -0.00028 - 0.5) + 1, arrowFrame.minY, floor(arrowFrame.width * 0.99986 - 0.5) - floor(arrowFrame.width * -0.00028 - 0.5) + 0, arrowFrame.height + 0.01)


        //// Group 2
        //// arrow Drawing
        var arrowPath = UIBezierPath()
        arrowPath.moveToPoint(CGPointMake(group2.minX + 0.95635 * group2.width, group2.minY + 0.56639 * group2.height))
        arrowPath.addCurveToPoint(CGPointMake(group2.minX + 0.92259 * group2.width, group2.minY + 0.57966 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.94638 * group2.width, group2.minY + 0.57229 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.93430 * group2.width, group2.minY + 0.57576 * group2.height))
        arrowPath.addLineToPoint(CGPointMake(group2.minX + 0.25695 * group2.width, group2.minY + 0.97389 * group2.height))
        arrowPath.addCurveToPoint(CGPointMake(group2.minX + 0.04408 * group2.width, group2.minY + 0.97389 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.19816 * group2.width, group2.minY + 1.00870 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.10286 * group2.width, group2.minY + 1.00870 * group2.height))
        arrowPath.addCurveToPoint(CGPointMake(group2.minX + 0.04408 * group2.width, group2.minY + 0.84783 * group2.height), controlPoint1: CGPointMake(group2.minX + -0.01469 * group2.width, group2.minY + 0.93908 * group2.height), controlPoint2: CGPointMake(group2.minX + -0.01469 * group2.width, group2.minY + 0.88264 * group2.height))
        arrowPath.addLineToPoint(CGPointMake(group2.minX + 0.63139 * group2.width, group2.minY + 0.50000 * group2.height))
        arrowPath.addLineToPoint(CGPointMake(group2.minX + 0.04408 * group2.width, group2.minY + 0.15217 * group2.height))
        arrowPath.addCurveToPoint(CGPointMake(group2.minX + 0.04408 * group2.width, group2.minY + 0.02611 * group2.height), controlPoint1: CGPointMake(group2.minX + -0.01469 * group2.width, group2.minY + 0.11736 * group2.height), controlPoint2: CGPointMake(group2.minX + -0.01469 * group2.width, group2.minY + 0.06092 * group2.height))
        arrowPath.addCurveToPoint(CGPointMake(group2.minX + 0.25695 * group2.width, group2.minY + 0.02611 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.10286 * group2.width, group2.minY + -0.00870 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.19816 * group2.width, group2.minY + -0.00870 * group2.height))
        arrowPath.addLineToPoint(CGPointMake(group2.minX + 0.92259 * group2.width, group2.minY + 0.42034 * group2.height))
        arrowPath.addCurveToPoint(CGPointMake(group2.minX + 0.95635 * group2.width, group2.minY + 0.43361 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.93430 * group2.width, group2.minY + 0.42424 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.94638 * group2.width, group2.minY + 0.42771 * group2.height))
        arrowPath.addCurveToPoint(CGPointMake(group2.minX + 0.99989 * group2.width, group2.minY + 0.50000 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.98719 * group2.width, group2.minY + 0.45188 * group2.height), controlPoint2: CGPointMake(group2.minX + 1.00141 * group2.width, group2.minY + 0.47608 * group2.height))
        arrowPath.addCurveToPoint(CGPointMake(group2.minX + 0.95635 * group2.width, group2.minY + 0.56639 * group2.height), controlPoint1: CGPointMake(group2.minX + 1.00141 * group2.width, group2.minY + 0.52392 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.98719 * group2.width, group2.minY + 0.54812 * group2.height))
        arrowPath.closePath()
        arrowColor.setFill()
        arrowPath.fill()




        //// Group
        //// arrow 2 Drawing
        var arrow2Path = UIBezierPath()
        arrow2Path.moveToPoint(CGPointMake(80.34, 14.16))
        arrow2Path.addCurveToPoint(CGPointMake(79.84, 14.49), controlPoint1: CGPointMake(80.19, 14.31), controlPoint2: CGPointMake(80.01, 14.39))
        arrow2Path.addLineToPoint(CGPointMake(69.85, 24.35))
        arrow2Path.addCurveToPoint(CGPointMake(66.66, 24.35), controlPoint1: CGPointMake(68.97, 25.22), controlPoint2: CGPointMake(67.54, 25.22))
        arrow2Path.addCurveToPoint(CGPointMake(66.66, 21.2), controlPoint1: CGPointMake(65.78, 23.48), controlPoint2: CGPointMake(65.78, 22.07))
        arrow2Path.addLineToPoint(CGPointMake(75.47, 12.5))
        arrow2Path.addLineToPoint(CGPointMake(66.66, 3.8))
        arrow2Path.addCurveToPoint(CGPointMake(66.66, 0.65), controlPoint1: CGPointMake(65.78, 2.93), controlPoint2: CGPointMake(65.78, 1.52))
        arrow2Path.addCurveToPoint(CGPointMake(69.85, 0.65), controlPoint1: CGPointMake(67.54, -0.22), controlPoint2: CGPointMake(68.97, -0.22))
        arrow2Path.addLineToPoint(CGPointMake(79.84, 10.51))
        arrow2Path.addCurveToPoint(CGPointMake(80.34, 10.84), controlPoint1: CGPointMake(80.01, 10.61), controlPoint2: CGPointMake(80.19, 10.69))
        arrow2Path.addCurveToPoint(CGPointMake(81, 12.5), controlPoint1: CGPointMake(80.81, 11.3), controlPoint2: CGPointMake(81.02, 11.9))
        arrow2Path.addCurveToPoint(CGPointMake(80.34, 14.16), controlPoint1: CGPointMake(81.02, 13.1), controlPoint2: CGPointMake(80.81, 13.7))
        arrow2Path.closePath()
        arrowColor.setFill()
        arrow2Path.fill()
    }

}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
